// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/bridge/v1/actions_root_snapshot.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ActionsReducedRootSnapshot stores the actions root committed at a Cosmos height.
type ActionsReducedRootSnapshot struct {
	// cosmos_block_height is the chain height at which the root was committed.
	CosmosBlockHeight int64 `protobuf:"varint,1,opt,name=cosmos_block_height,json=cosmosBlockHeight,proto3" json:"cosmos_block_height,omitempty"`
	// actions_reduced_root is the canonical Pallas field encoding of the root.
	ActionsReducedRoot []byte `protobuf:"bytes,2,opt,name=actions_reduced_root,json=actionsReducedRoot,proto3" json:"actions_reduced_root,omitempty"`
}

func (m *ActionsReducedRootSnapshot) Reset()         { *m = ActionsReducedRootSnapshot{} }
func (m *ActionsReducedRootSnapshot) String() string { return proto.CompactTextString(m) }
func (*ActionsReducedRootSnapshot) ProtoMessage()    {}
func (*ActionsReducedRootSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_91dda1aba95bedff, []int{0}
}
func (m *ActionsReducedRootSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActionsReducedRootSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActionsReducedRootSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActionsReducedRootSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionsReducedRootSnapshot.Merge(m, src)
}
func (m *ActionsReducedRootSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *ActionsReducedRootSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionsReducedRootSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_ActionsReducedRootSnapshot proto.InternalMessageInfo

func (m *ActionsReducedRootSnapshot) GetCosmosBlockHeight() int64 {
	if m != nil {
		return m.CosmosBlockHeight
	}
	return 0
}

func (m *ActionsReducedRootSnapshot) GetActionsReducedRoot() []byte {
	if m != nil {
		return m.ActionsReducedRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*ActionsReducedRootSnapshot)(nil), "pulsarchain.bridge.v1.ActionsReducedRootSnapshot")
}

func init() {
	proto.RegisterFile("pulsarchain/bridge/v1/actions_root_snapshot.proto", fileDescriptor_91dda1aba95bedff)
}

var fileDescriptor_91dda1aba95bedff = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x3d, 0x4e, 0xc3, 0x30,
	0x14, 0x8e, 0x41, 0x62, 0x88, 0x58, 0x1a, 0x8a, 0x54, 0x65, 0xb0, 0x2a, 0xa6, 0x2e, 0xb5, 0x6b,
	0x71, 0x02, 0x3a, 0x21, 0xb1, 0x85, 0x8d, 0x25, 0x72, 0x1c, 0xcb, 0xb6, 0x68, 0xfc, 0x22, 0xdb,
	0xa9, 0x60, 0xe1, 0x0c, 0x1c, 0x8b, 0xb1, 0x23, 0x23, 0x4a, 0x2e, 0x82, 0x6a, 0x03, 0x42, 0xea,
	0x62, 0x3d, 0xf9, 0x7b, 0xef, 0xfb, 0xcb, 0x59, 0x3f, 0xec, 0x3c, 0x77, 0x42, 0x73, 0x63, 0x69,
	0xe3, 0x4c, 0xab, 0x24, 0xdd, 0x33, 0xca, 0x45, 0x30, 0x60, 0x7d, 0xed, 0x00, 0x42, 0xed, 0x2d,
	0xef, 0xbd, 0x86, 0x40, 0x7a, 0x07, 0x01, 0x8a, 0xeb, 0x7f, 0x27, 0x24, 0x9d, 0x90, 0x3d, 0x2b,
	0x67, 0xbc, 0x33, 0x16, 0x68, 0x7c, 0xd3, 0x66, 0x39, 0x57, 0xa0, 0x20, 0x8e, 0xf4, 0x38, 0xa5,
	0xdf, 0x9b, 0xb7, 0xbc, 0xbc, 0x4b, 0xf4, 0x95, 0x6c, 0x07, 0x21, 0xdb, 0x0a, 0x20, 0x3c, 0xfe,
	0x68, 0x14, 0x24, 0xbf, 0x12, 0xe0, 0x3b, 0xf0, 0x75, 0xb3, 0x03, 0xf1, 0x5c, 0x6b, 0x69, 0x94,
	0x0e, 0x0b, 0xb4, 0x44, 0xab, 0xf3, 0x6a, 0x96, 0xa0, 0xed, 0x11, 0xb9, 0x8f, 0x40, 0xb1, 0xc9,
	0xe7, 0x7f, 0x66, 0x13, 0x5d, 0x34, 0xbd, 0x38, 0x5b, 0xa2, 0xd5, 0x65, 0x55, 0xf0, 0x13, 0xa5,
	0xed, 0xc3, 0xc7, 0x88, 0xd1, 0x61, 0xc4, 0xe8, 0x6b, 0xc4, 0xe8, 0x7d, 0xc2, 0xd9, 0x61, 0xc2,
	0xd9, 0xe7, 0x84, 0xb3, 0x27, 0xa6, 0x4c, 0xd0, 0x43, 0x43, 0x04, 0x74, 0xd4, 0x42, 0x2b, 0xd9,
	0x86, 0xad, 0x0d, 0xd0, 0x94, 0x77, 0x9d, 0x3a, 0x7a, 0xf9, 0x6d, 0x29, 0xbc, 0xf6, 0xd2, 0x37,
	0x17, 0x31, 0xd3, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x55, 0x45, 0xc8, 0x48, 0x01,
	0x00, 0x00,
}

func (m *ActionsReducedRootSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActionsReducedRootSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActionsReducedRootSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActionsReducedRoot) > 0 {
		i -= len(m.ActionsReducedRoot)
		copy(dAtA[i:], m.ActionsReducedRoot)
		i = encodeVarintActionsRootSnapshot(dAtA, i, uint64(len(m.ActionsReducedRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.CosmosBlockHeight != 0 {
		i = encodeVarintActionsRootSnapshot(dAtA, i, uint64(m.CosmosBlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintActionsRootSnapshot(dAtA []byte, offset int, v uint64) int {
	offset -= sovActionsRootSnapshot(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ActionsReducedRootSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CosmosBlockHeight != 0 {
		n += 1 + sovActionsRootSnapshot(uint64(m.CosmosBlockHeight))
	}
	l = len(m.ActionsReducedRoot)
	if l > 0 {
		n += 1 + l + sovActionsRootSnapshot(uint64(l))
	}
	return n
}

func sovActionsRootSnapshot(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozActionsRootSnapshot(x uint64) (n int) {
	return sovActionsRootSnapshot(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ActionsReducedRootSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActionsRootSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActionsReducedRootSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActionsReducedRootSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosBlockHeight", wireType)
			}
			m.CosmosBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActionsRootSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CosmosBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionsReducedRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActionsRootSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthActionsRootSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthActionsRootSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionsReducedRoot = append(m.ActionsReducedRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.ActionsReducedRoot == nil {
				m.ActionsReducedRoot = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActionsRootSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActionsRootSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActionsRootSnapshot(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActionsRootSnapshot
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActionsRootSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActionsRootSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthActionsRootSnapshot
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupActionsRootSnapshot
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthActionsRootSnapshot
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthActionsRootSnapshot        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActionsRootSnapshot          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupActionsRootSnapshot = fmt.Errorf("proto: unexpected end of group")
)
