// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/bridge/v1/bridge_state.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BridgeState stores the bridge's processed Mina cursor.
type BridgeState struct {
	// latest_fetched_mina_height is the latest Mina height processed by the bridge.
	LatestFetchedMinaHeight int64 `protobuf:"varint,1,opt,name=latest_fetched_mina_height,json=latestFetchedMinaHeight,proto3" json:"latest_fetched_mina_height,omitempty"`
	// action_hashes is the cumulative ordered canonical hash batch built
	// from successful PushNewActions calls in the same Cosmos block. Execution
	// order is part of the root reconstruction contract.
	ActionHashes []string `protobuf:"bytes,2,rep,name=action_hashes,json=actionHashes,proto3" json:"action_hashes,omitempty"`
	// action_hashes_cosmos_block_height is the Cosmos block height of the
	// batch represented by action_hashes.
	ActionHashesCosmosBlockHeight int64 `protobuf:"varint,3,opt,name=action_hashes_cosmos_block_height,json=actionHashesCosmosBlockHeight,proto3" json:"action_hashes_cosmos_block_height,omitempty"`
	// start_mina_height is the starting Mina cursor for the current query batch.
	StartMinaHeight int64 `protobuf:"varint,4,opt,name=start_mina_height,json=startMinaHeight,proto3" json:"start_mina_height,omitempty"`
}

func (m *BridgeState) Reset()         { *m = BridgeState{} }
func (m *BridgeState) String() string { return proto.CompactTextString(m) }
func (*BridgeState) ProtoMessage()    {}
func (*BridgeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f537cf215cb7f9d, []int{0}
}
func (m *BridgeState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeState.Merge(m, src)
}
func (m *BridgeState) XXX_Size() int {
	return m.Size()
}
func (m *BridgeState) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeState.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeState proto.InternalMessageInfo

func (m *BridgeState) GetLatestFetchedMinaHeight() int64 {
	if m != nil {
		return m.LatestFetchedMinaHeight
	}
	return 0
}

func (m *BridgeState) GetActionHashes() []string {
	if m != nil {
		return m.ActionHashes
	}
	return nil
}

func (m *BridgeState) GetActionHashesCosmosBlockHeight() int64 {
	if m != nil {
		return m.ActionHashesCosmosBlockHeight
	}
	return 0
}

func (m *BridgeState) GetStartMinaHeight() int64 {
	if m != nil {
		return m.StartMinaHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*BridgeState)(nil), "pulsarchain.bridge.v1.BridgeState")
}

func init() {
	proto.RegisterFile("pulsarchain/bridge/v1/bridge_state.proto", fileDescriptor_9f537cf215cb7f9d)
}

var fileDescriptor_9f537cf215cb7f9d = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xec, 0x30,
	0x14, 0x86, 0x9b, 0xdb, 0x8b, 0x60, 0x54, 0xc4, 0x82, 0x38, 0x08, 0x86, 0x51, 0x37, 0x45, 0x98,
	0xd6, 0xe2, 0xd2, 0x5d, 0x05, 0x29, 0x88, 0x9b, 0x71, 0xe7, 0x26, 0xa4, 0x69, 0x6c, 0x82, 0x6d,
	0x53, 0x9a, 0x33, 0x83, 0xbe, 0x85, 0x8f, 0xe5, 0x72, 0x96, 0x2e, 0xa5, 0xc5, 0xf7, 0x90, 0x49,
	0x66, 0x70, 0x66, 0x97, 0x9c, 0xff, 0x3b, 0xfc, 0x87, 0x0f, 0x87, 0xed, 0xac, 0x32, 0xac, 0xe3,
	0x92, 0xa9, 0x26, 0xce, 0x3b, 0x55, 0x94, 0x22, 0x9e, 0x27, 0xab, 0x17, 0x35, 0xc0, 0x40, 0x44,
	0x6d, 0xa7, 0x41, 0x07, 0xc7, 0x1b, 0x64, 0xe4, 0xf2, 0x68, 0x9e, 0x5c, 0xfc, 0x20, 0xbc, 0x97,
	0xda, 0xdf, 0xd3, 0x12, 0x0e, 0x6e, 0xf1, 0x69, 0xc5, 0x40, 0x18, 0xa0, 0x2f, 0x02, 0xb8, 0x14,
	0x05, 0xad, 0x55, 0xc3, 0xa8, 0x14, 0xaa, 0x94, 0x30, 0x42, 0x63, 0x14, 0xfa, 0xd3, 0x13, 0x47,
	0xdc, 0x3b, 0xe0, 0x51, 0x35, 0x2c, 0xb3, 0x71, 0x70, 0x89, 0x0f, 0x18, 0x07, 0xa5, 0x1b, 0x2a,
	0x99, 0x91, 0xc2, 0x8c, 0xfe, 0x8d, 0xfd, 0x70, 0x77, 0xba, 0xef, 0x86, 0x99, 0x9d, 0x05, 0x19,
	0x3e, 0xdf, 0x82, 0x28, 0xd7, 0xa6, 0xd6, 0x86, 0xe6, 0x95, 0xe6, 0xaf, 0xeb, 0x22, 0xdf, 0x16,
	0x9d, 0x6d, 0x2e, 0xde, 0x59, 0x2c, 0x5d, 0x52, 0xab, 0xba, 0x2b, 0x7c, 0x64, 0x80, 0x75, 0xb0,
	0x75, 0xe2, 0x7f, 0xbb, 0x79, 0x68, 0x83, 0xbf, 0xd3, 0xd2, 0x87, 0xcf, 0x9e, 0xa0, 0x45, 0x4f,
	0xd0, 0x77, 0x4f, 0xd0, 0xc7, 0x40, 0xbc, 0xc5, 0x40, 0xbc, 0xaf, 0x81, 0x78, 0xcf, 0x49, 0xa9,
	0x40, 0xce, 0xf2, 0x88, 0xeb, 0x3a, 0x6e, 0x74, 0x21, 0x92, 0xeb, 0x64, 0xa2, 0x74, 0xec, 0x74,
	0x4d, 0x9c, 0xd9, 0xb7, 0xb5, 0x5b, 0x78, 0x6f, 0x85, 0xc9, 0x77, 0xac, 0xd2, 0x9b, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x28, 0xf9, 0xf3, 0x1a, 0x7e, 0x01, 0x00, 0x00,
}

func (m *BridgeState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StartMinaHeight != 0 {
		i = encodeVarintBridgeState(dAtA, i, uint64(m.StartMinaHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.ActionHashesCosmosBlockHeight != 0 {
		i = encodeVarintBridgeState(dAtA, i, uint64(m.ActionHashesCosmosBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ActionHashes) > 0 {
		for iNdEx := len(m.ActionHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ActionHashes[iNdEx])
			copy(dAtA[i:], m.ActionHashes[iNdEx])
			i = encodeVarintBridgeState(dAtA, i, uint64(len(m.ActionHashes[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.LatestFetchedMinaHeight != 0 {
		i = encodeVarintBridgeState(dAtA, i, uint64(m.LatestFetchedMinaHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBridgeState(dAtA []byte, offset int, v uint64) int {
	offset -= sovBridgeState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BridgeState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LatestFetchedMinaHeight != 0 {
		n += 1 + sovBridgeState(uint64(m.LatestFetchedMinaHeight))
	}
	if len(m.ActionHashes) > 0 {
		for _, s := range m.ActionHashes {
			l = len(s)
			n += 1 + l + sovBridgeState(uint64(l))
		}
	}
	if m.ActionHashesCosmosBlockHeight != 0 {
		n += 1 + sovBridgeState(uint64(m.ActionHashesCosmosBlockHeight))
	}
	if m.StartMinaHeight != 0 {
		n += 1 + sovBridgeState(uint64(m.StartMinaHeight))
	}
	return n
}

func sovBridgeState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBridgeState(x uint64) (n int) {
	return sovBridgeState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BridgeState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridgeState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestFetchedMinaHeight", wireType)
			}
			m.LatestFetchedMinaHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestFetchedMinaHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionHashes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridgeState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridgeState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionHashes = append(m.ActionHashes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionHashesCosmosBlockHeight", wireType)
			}
			m.ActionHashesCosmosBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionHashesCosmosBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartMinaHeight", wireType)
			}
			m.StartMinaHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartMinaHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBridgeState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridgeState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBridgeState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBridgeState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBridgeState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBridgeState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBridgeState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBridgeState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBridgeState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBridgeState = fmt.Errorf("proto: unexpected end of group")
)
