// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/bridge/v1/bridge_state.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BridgeState struct {
	LatestFetchedMinaHeight int64  `protobuf:"varint,1,opt,name=latest_fetched_mina_height,json=latestFetchedMinaHeight,proto3" json:"latest_fetched_mina_height,omitempty"`
	ActionsReducedRoot      []byte `protobuf:"bytes,2,opt,name=actions_reduced_root,json=actionsReducedRoot,proto3" json:"actions_reduced_root,omitempty"`
}

func (m *BridgeState) Reset()         { *m = BridgeState{} }
func (m *BridgeState) String() string { return proto.CompactTextString(m) }
func (*BridgeState) ProtoMessage()    {}
func (*BridgeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f537cf215cb7f9d, []int{0}
}
func (m *BridgeState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeState.Merge(m, src)
}
func (m *BridgeState) XXX_Size() int {
	return m.Size()
}
func (m *BridgeState) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeState.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeState proto.InternalMessageInfo

func (m *BridgeState) GetLatestFetchedMinaHeight() int64 {
	if m != nil {
		return m.LatestFetchedMinaHeight
	}
	return 0
}

func (m *BridgeState) GetActionsReducedRoot() []byte {
	if m != nil {
		return m.ActionsReducedRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*BridgeState)(nil), "pulsarchain.bridge.v1.BridgeState")
}

func init() {
	proto.RegisterFile("pulsarchain/bridge/v1/bridge_state.proto", fileDescriptor_9f537cf215cb7f9d)
}

var fileDescriptor_9f537cf215cb7f9d = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0x2f, 0x0a, 0x0e, 0xd5, 0xa9, 0x28, 0x1e, 0x0e, 0xe1, 0x70, 0xea, 0x72, 0xed, 0x05,
	0x47, 0xb7, 0x1b, 0x44, 0x10, 0x97, 0xba, 0xb9, 0x84, 0x34, 0xf9, 0x6c, 0x02, 0x77, 0xf9, 0x4a,
	0xf2, 0xf5, 0x50, 0xf0, 0x47, 0xf8, 0xb3, 0x1c, 0x6f, 0x74, 0x94, 0xf6, 0x8f, 0x88, 0xcd, 0x09,
	0x6e, 0xef, 0xcb, 0xf3, 0x2c, 0x4f, 0x56, 0x74, 0xfd, 0x26, 0xaa, 0xa0, 0xad, 0x72, 0xbe, 0x6a,
	0x82, 0x33, 0x2d, 0x54, 0x3b, 0x71, 0x58, 0x32, 0x92, 0x22, 0x28, 0xbb, 0x80, 0x84, 0xf9, 0xc5,
	0x3f, 0xb3, 0x4c, 0xbc, 0xdc, 0x89, 0xeb, 0xf7, 0xec, 0x74, 0x3d, 0x9d, 0xa7, 0x5f, 0x37, 0xbf,
	0xcd, 0xae, 0x36, 0x8a, 0x20, 0x92, 0x7c, 0x01, 0xd2, 0x16, 0x8c, 0xdc, 0x3a, 0xaf, 0xa4, 0x05,
	0xd7, 0x5a, 0x9a, 0xb3, 0x05, 0x2b, 0x8e, 0xeb, 0xcb, 0x64, 0xdc, 0x25, 0xe1, 0xd1, 0x79, 0x75,
	0x3f, 0xe1, 0x7c, 0x95, 0x9d, 0x2b, 0x4d, 0x0e, 0x7d, 0x94, 0x01, 0x4c, 0xaf, 0xc1, 0xc8, 0x80,
	0x48, 0xf3, 0xa3, 0x05, 0x2b, 0xce, 0xea, 0xfc, 0xc0, 0xea, 0x84, 0x6a, 0x44, 0x5a, 0x3f, 0x7c,
	0x0e, 0x9c, 0xed, 0x07, 0xce, 0xbe, 0x07, 0xce, 0x3e, 0x46, 0x3e, 0xdb, 0x8f, 0x7c, 0xf6, 0x35,
	0xf2, 0xd9, 0xb3, 0x68, 0x1d, 0xd9, 0xbe, 0x29, 0x35, 0x6e, 0x2b, 0x8f, 0x06, 0xc4, 0x4a, 0x2c,
	0x1d, 0x56, 0x29, 0x62, 0x99, 0x7a, 0x5f, 0xff, 0x8a, 0xe9, 0xad, 0x83, 0xd8, 0x9c, 0x4c, 0xa1,
	0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x37, 0xe4, 0x84, 0x7a, 0x14, 0x01, 0x00, 0x00,
}

func (m *BridgeState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActionsReducedRoot) > 0 {
		i -= len(m.ActionsReducedRoot)
		copy(dAtA[i:], m.ActionsReducedRoot)
		i = encodeVarintBridgeState(dAtA, i, uint64(len(m.ActionsReducedRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.LatestFetchedMinaHeight != 0 {
		i = encodeVarintBridgeState(dAtA, i, uint64(m.LatestFetchedMinaHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBridgeState(dAtA []byte, offset int, v uint64) int {
	offset -= sovBridgeState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BridgeState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LatestFetchedMinaHeight != 0 {
		n += 1 + sovBridgeState(uint64(m.LatestFetchedMinaHeight))
	}
	l = len(m.ActionsReducedRoot)
	if l > 0 {
		n += 1 + l + sovBridgeState(uint64(l))
	}
	return n
}

func sovBridgeState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBridgeState(x uint64) (n int) {
	return sovBridgeState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BridgeState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridgeState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestFetchedMinaHeight", wireType)
			}
			m.LatestFetchedMinaHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestFetchedMinaHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionsReducedRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBridgeState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBridgeState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionsReducedRoot = append(m.ActionsReducedRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.ActionsReducedRoot == nil {
				m.ActionsReducedRoot = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBridgeState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridgeState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBridgeState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBridgeState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBridgeState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBridgeState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBridgeState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBridgeState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBridgeState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBridgeState = fmt.Errorf("proto: unexpected end of group")
)
