// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/bridge/v1/bridge_state.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BridgeState stores the bridge's processed Mina cursor.
type BridgeState struct {
	// latest_fetched_mina_height is the latest Mina height processed by the bridge.
	LatestFetchedMinaHeight int64 `protobuf:"varint,1,opt,name=latest_fetched_mina_height,json=latestFetchedMinaHeight,proto3" json:"latest_fetched_mina_height,omitempty"`
}

func (m *BridgeState) Reset()         { *m = BridgeState{} }
func (m *BridgeState) String() string { return proto.CompactTextString(m) }
func (*BridgeState) ProtoMessage()    {}
func (*BridgeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f537cf215cb7f9d, []int{0}
}
func (m *BridgeState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeState.Merge(m, src)
}
func (m *BridgeState) XXX_Size() int {
	return m.Size()
}
func (m *BridgeState) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeState.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeState proto.InternalMessageInfo

func (m *BridgeState) GetLatestFetchedMinaHeight() int64 {
	if m != nil {
		return m.LatestFetchedMinaHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*BridgeState)(nil), "pulsarchain.bridge.v1.BridgeState")
}

func init() {
	proto.RegisterFile("pulsarchain/bridge/v1/bridge_state.proto", fileDescriptor_9f537cf215cb7f9d)
}

var fileDescriptor_9f537cf215cb7f9d = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0x37, 0x9e, 0x88, 0xac, 0x8d, 0x1c, 0x88, 0x22, 0x12, 0xc4, 0xea, 0x9a, 0xdb, 0x35,
	0x58, 0xda, 0x5d, 0x21, 0xa2, 0xd8, 0x9c, 0x9d, 0x4d, 0xc8, 0x26, 0xe3, 0x26, 0x70, 0x97, 0x59,
	0x92, 0xc9, 0xa1, 0x6f, 0xe1, 0x63, 0x59, 0x5e, 0x69, 0x29, 0xbb, 0x2f, 0x22, 0x6e, 0x14, 0xae,
	0x9b, 0xe1, 0xfb, 0x8a, 0xff, 0x2b, 0x67, 0x5d, 0x5a, 0x45, 0x15, 0xb4, 0x55, 0xce, 0xd7, 0x4d,
	0x70, 0xa6, 0x85, 0x7a, 0x23, 0xfe, 0x2e, 0x19, 0x49, 0x11, 0x54, 0x5d, 0x40, 0xc2, 0xe9, 0xc9,
	0x8e, 0x59, 0x65, 0x5e, 0x6d, 0xc4, 0x95, 0x2f, 0x8f, 0x16, 0xe3, 0xf3, 0xfc, 0xeb, 0x4e, 0x6f,
	0xcb, 0xf3, 0x95, 0x22, 0x88, 0x24, 0x5f, 0x81, 0xb4, 0x05, 0x23, 0xd7, 0xce, 0x2b, 0x69, 0xc1,
	0xb5, 0x96, 0xce, 0xd8, 0x25, 0x9b, 0x4d, 0x96, 0xa7, 0xd9, 0xb8, 0xcb, 0xc2, 0x93, 0xf3, 0xea,
	0x7e, 0xc4, 0x0f, 0xfb, 0x87, 0x7b, 0xc7, 0x93, 0xe5, 0x85, 0x4e, 0x21, 0x80, 0x27, 0xa9, 0x34,
	0x39, 0xf4, 0x51, 0x06, 0x30, 0x49, 0x83, 0x91, 0x01, 0x91, 0x16, 0x8f, 0x9f, 0x3d, 0x67, 0xdb,
	0x9e, 0xb3, 0xef, 0x9e, 0xb3, 0x8f, 0x81, 0x17, 0xdb, 0x81, 0x17, 0x5f, 0x03, 0x2f, 0x5e, 0x44,
	0xeb, 0xc8, 0xa6, 0xa6, 0xd2, 0xb8, 0xae, 0x3d, 0x1a, 0x10, 0xd7, 0x62, 0xee, 0xb0, 0xce, 0xb3,
	0xe7, 0xb9, 0xf0, 0xed, 0xbf, 0x91, 0xde, 0x3b, 0x88, 0xcd, 0xc1, 0x98, 0x76, 0xf3, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x9a, 0x56, 0xc3, 0x5c, 0x06, 0x01, 0x00, 0x00,
}

func (m *BridgeState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LatestFetchedMinaHeight != 0 {
		i = encodeVarintBridgeState(dAtA, i, uint64(m.LatestFetchedMinaHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBridgeState(dAtA []byte, offset int, v uint64) int {
	offset -= sovBridgeState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BridgeState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LatestFetchedMinaHeight != 0 {
		n += 1 + sovBridgeState(uint64(m.LatestFetchedMinaHeight))
	}
	return n
}

func sovBridgeState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBridgeState(x uint64) (n int) {
	return sovBridgeState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BridgeState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridgeState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestFetchedMinaHeight", wireType)
			}
			m.LatestFetchedMinaHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestFetchedMinaHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBridgeState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridgeState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBridgeState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBridgeState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridgeState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBridgeState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBridgeState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBridgeState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBridgeState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBridgeState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBridgeState = fmt.Errorf("proto: unexpected end of group")
)
