version: 1
validation: sovereign
default_denom: pmina
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000pmina
- name: bob
  coins:
  - 10000token
  - 100000000pmina
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000pmina
  app:
      vote_extension:
        priv_key: "OhOfQtGMXqcrbfCRPEe4DjLUNHaOcD3RrWuRPBGO82M="
- name: validator1
  bonded: 200000000pmina
- name: validator2
  bonded: 100000000pmina

genesis:
  app_state:
    keyregistry:
      params: {}
      user_key_pairs:
        # Mina compressed public key placeholder: zero bytes, 33 bytes.
        #- mina_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          # Cosmos user public key placeholder: secp256k1 compressed, zero bytes, 33 bytes.
          #cosmos_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      validator_key_pairs:
       # - mina_key: "3IvK1eWmmcfdlIb+T04+ck9Q5bjbqHqiT0ucGJITzyY="
        #  cosmos_key: "A8saw69s1DQWvUjseeOtG8hGavmYiInrQ5M1aOPa4QkP"
