package ante

import (
	"encoding/hex"
	"testing"

	"github.com/stretchr/testify/require"

	keyregistrytypes "github.com/node101-io/pulsar-chain/x/keyregistry/types"
)

func TestBuildTxSigningChallengeIsDeterministic(t *testing.T) {
	first, err := BuildTxSigningChallenge([]byte("payload"))
	require.NoError(t, err)
	second, err := BuildTxSigningChallenge([]byte("payload"))
	require.NoError(t, err)

	require.Equal(t, first.Bytes(), second.Bytes())
}

func TestBuildTxSigningChallengeSeparatesPayloads(t *testing.T) {
	first, err := BuildTxSigningChallenge([]byte("payload-a"))
	require.NoError(t, err)
	second, err := BuildTxSigningChallenge([]byte("payload-b"))
	require.NoError(t, err)

	require.NotEqual(t, first.Bytes(), second.Bytes())
}

func TestBuildTxSigningChallengeRejectsEmptySignBytes(t *testing.T) {
	_, err := BuildTxSigningChallenge(nil)
	require.Error(t, err)
	_, err = BuildTxSigningChallenge([]byte{})
	require.Error(t, err)
}

// The derivation is a wire contract: pulsar-chain-client mirrors it in
// TypeScript against this exact vector (the keySigningChallenge pattern). If
// this test breaks, the derivation changed and every wallet-signed tx built by
// an existing client stops verifying — that is a consensus-facing decision,
// never a refactor. Change the prefix version instead.
//
// Vector generated by this implementation at introduction (mina-signer-go
// 58fec0da0b49): challenge for sign bytes "pulsar-tx-vector-01", hex-encoded
// FieldElement.Bytes().
func TestBuildTxSigningChallengeVector(t *testing.T) {
	challenge, err := BuildTxSigningChallenge([]byte("pulsar-tx-vector-01"))
	require.NoError(t, err)

	require.Equal(t,
		"185cf93846576559d5abe9e6c8b5d637940727c9516d1f346a775fe57d897cff",
		hex.EncodeToString(challenge.Bytes()),
	)
}

// A tx-auth challenge and a key-registry challenge over comparable input must
// never coincide: the prefixes are the only wall between "I authorize this
// transaction" and "I bind this key". This cannot realistically collide by
// accident — the test documents the invariant so a future prefix change that
// unifies them fails loudly.
func TestBuildTxSigningChallengeDomainSeparatedFromKeyRegistry(t *testing.T) {
	cosmosKey := make([]byte, 33)
	cosmosKey[0] = 0x02
	minaKey := minaPublicKeyBytesForTest(t, newMinaPrivateKeyForTest(t, 0x07))

	registration, err := keyregistrytypes.BuildKeySigningChallenge(keyregistrytypes.KeySigningChallengeInput{
		ChainID:          "mytestnet",
		Operation:        keyregistrytypes.KeySigningOperation_KEY_SIGNING_OPERATION_REGISTER,
		ActorType:        keyregistrytypes.ActorType_ACTOR_TYPE_USER,
		CosmosPublicKey:  cosmosKey,
		NewMinaPublicKey: minaKey,
	})
	require.NoError(t, err)

	// The same bytes the registration challenge was built from, fed to the tx
	// derivation — the closest an attacker can steer the two inputs together.
	txChallenge, err := BuildTxSigningChallenge(registration.Bytes())
	require.NoError(t, err)

	require.NotEqual(t, registration.Bytes(), txChallenge.Bytes())
}
