// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/verification/v1/commitment_reveal.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProofCommitmentReveal opens the left leaf and supplies the right sibling.
type ProofCommitmentReveal struct {
	FirstSecretSalt  []byte            `protobuf:"bytes,1,opt,name=first_secret_salt,json=firstSecretSalt,proto3" json:"first_secret_salt,omitempty"`
	FirstBlockProofs []ProofCommitment `protobuf:"bytes,2,rep,name=first_block_proofs,json=firstBlockProofs,proto3" json:"first_block_proofs"`
	SecondLeafHash   []byte            `protobuf:"bytes,3,opt,name=second_leaf_hash,json=secondLeafHash,proto3" json:"second_leaf_hash,omitempty"`
}

func (m *ProofCommitmentReveal) Reset()         { *m = ProofCommitmentReveal{} }
func (m *ProofCommitmentReveal) String() string { return proto.CompactTextString(m) }
func (*ProofCommitmentReveal) ProtoMessage()    {}
func (*ProofCommitmentReveal) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd29fb3a464cb34, []int{0}
}
func (m *ProofCommitmentReveal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofCommitmentReveal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofCommitmentReveal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofCommitmentReveal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofCommitmentReveal.Merge(m, src)
}
func (m *ProofCommitmentReveal) XXX_Size() int {
	return m.Size()
}
func (m *ProofCommitmentReveal) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofCommitmentReveal.DiscardUnknown(m)
}

var xxx_messageInfo_ProofCommitmentReveal proto.InternalMessageInfo

func (m *ProofCommitmentReveal) GetFirstSecretSalt() []byte {
	if m != nil {
		return m.FirstSecretSalt
	}
	return nil
}

func (m *ProofCommitmentReveal) GetFirstBlockProofs() []ProofCommitment {
	if m != nil {
		return m.FirstBlockProofs
	}
	return nil
}

func (m *ProofCommitmentReveal) GetSecondLeafHash() []byte {
	if m != nil {
		return m.SecondLeafHash
	}
	return nil
}

func init() {
	proto.RegisterType((*ProofCommitmentReveal)(nil), "pulsarchain.verification.v1.ProofCommitmentReveal")
}

func init() {
	proto.RegisterFile("pulsarchain/verification/v1/commitment_reveal.proto", fileDescriptor_3bd29fb3a464cb34)
}

var fileDescriptor_3bd29fb3a464cb34 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x3f, 0x4f, 0x32, 0x31,
	0x18, 0xbf, 0x7b, 0x79, 0xe3, 0x70, 0x1a, 0xc5, 0x8b, 0x26, 0x04, 0x93, 0x4a, 0x9c, 0x88, 0x91,
	0xd6, 0x83, 0xc1, 0x1d, 0x17, 0x07, 0x07, 0x85, 0xcd, 0xa5, 0x96, 0xd2, 0xe3, 0x1a, 0x7b, 0xf7,
	0x5c, 0xda, 0x72, 0xd1, 0x6f, 0xe1, 0xc7, 0x62, 0x93, 0xd1, 0xc9, 0x18, 0xf8, 0x22, 0xe6, 0xda,
	0x44, 0xd1, 0x81, 0xad, 0x79, 0x7e, 0x7f, 0xfb, 0x8b, 0x06, 0xe5, 0x5c, 0x19, 0xa6, 0x79, 0xc6,
	0x64, 0x41, 0x2a, 0xa1, 0x65, 0x2a, 0x39, 0xb3, 0x12, 0x0a, 0x52, 0x25, 0x84, 0x43, 0x9e, 0x4b,
	0x9b, 0x8b, 0xc2, 0x52, 0x2d, 0x2a, 0xc1, 0x14, 0x2e, 0x35, 0x58, 0x88, 0x4f, 0x36, 0x44, 0x78,
	0x53, 0x84, 0xab, 0xa4, 0x7d, 0x34, 0x83, 0x19, 0x38, 0x1e, 0xa9, 0x5f, 0x5e, 0xd2, 0xee, 0x6f,
	0xcb, 0x29, 0x35, 0x40, 0x4a, 0x7f, 0xd2, 0xbc, 0xe6, 0xec, 0x2d, 0x8c, 0x8e, 0xef, 0x6a, 0xe8,
	0xfa, 0x1b, 0x19, 0xb9, 0x1a, 0xf1, 0x79, 0x74, 0x98, 0x4a, 0x6d, 0x2c, 0x35, 0x82, 0x6b, 0x61,
	0xa9, 0x61, 0xca, 0xb6, 0xc2, 0x4e, 0xd8, 0xdd, 0x1b, 0x1d, 0x38, 0x60, 0xec, 0xee, 0x63, 0xa6,
	0x6c, 0xfc, 0x18, 0xc5, 0x9e, 0x3b, 0x51, 0xc0, 0x9f, 0xa8, 0xcb, 0x32, 0xad, 0x7f, 0x9d, 0x46,
	0x77, 0xb7, 0x7f, 0x81, 0xb7, 0xfc, 0x04, 0xff, 0xc9, 0x1e, 0xfe, 0x5f, 0x7c, 0x9c, 0x06, 0xa3,
	0xa6, 0x73, 0x1b, 0xd6, 0x66, 0x8e, 0x60, 0xe2, 0x6e, 0xd4, 0x34, 0x82, 0x43, 0x31, 0xa5, 0x4a,
	0xb0, 0x94, 0x66, 0xcc, 0x64, 0xad, 0x86, 0x2b, 0xb3, 0xef, 0xef, 0xb7, 0x82, 0xa5, 0x37, 0xcc,
	0x64, 0xc3, 0xfb, 0xc5, 0x0a, 0x85, 0xcb, 0x15, 0x0a, 0x3f, 0x57, 0x28, 0x7c, 0x5d, 0xa3, 0x60,
	0xb9, 0x46, 0xc1, 0xfb, 0x1a, 0x05, 0x0f, 0x57, 0x33, 0x69, 0xb3, 0xf9, 0x04, 0x73, 0xc8, 0x49,
	0x01, 0x53, 0x91, 0x5c, 0x26, 0x3d, 0x09, 0xc4, 0xd7, 0xeb, 0xf9, 0xd9, 0x9e, 0x7f, 0x0f, 0x67,
	0x5f, 0x4a, 0x61, 0x26, 0x3b, 0x6e, 0xab, 0xc1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xd7,
	0xfb, 0xd5, 0xc9, 0x01, 0x00, 0x00,
}

func (m *ProofCommitmentReveal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofCommitmentReveal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofCommitmentReveal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SecondLeafHash) > 0 {
		i -= len(m.SecondLeafHash)
		copy(dAtA[i:], m.SecondLeafHash)
		i = encodeVarintCommitmentReveal(dAtA, i, uint64(len(m.SecondLeafHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FirstBlockProofs) > 0 {
		for iNdEx := len(m.FirstBlockProofs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FirstBlockProofs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCommitmentReveal(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.FirstSecretSalt) > 0 {
		i -= len(m.FirstSecretSalt)
		copy(dAtA[i:], m.FirstSecretSalt)
		i = encodeVarintCommitmentReveal(dAtA, i, uint64(len(m.FirstSecretSalt)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommitmentReveal(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommitmentReveal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProofCommitmentReveal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FirstSecretSalt)
	if l > 0 {
		n += 1 + l + sovCommitmentReveal(uint64(l))
	}
	if len(m.FirstBlockProofs) > 0 {
		for _, e := range m.FirstBlockProofs {
			l = e.Size()
			n += 1 + l + sovCommitmentReveal(uint64(l))
		}
	}
	l = len(m.SecondLeafHash)
	if l > 0 {
		n += 1 + l + sovCommitmentReveal(uint64(l))
	}
	return n
}

func sovCommitmentReveal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommitmentReveal(x uint64) (n int) {
	return sovCommitmentReveal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProofCommitmentReveal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommitmentReveal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofCommitmentReveal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofCommitmentReveal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstSecretSalt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitmentReveal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommitmentReveal
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommitmentReveal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstSecretSalt = append(m.FirstSecretSalt[:0], dAtA[iNdEx:postIndex]...)
			if m.FirstSecretSalt == nil {
				m.FirstSecretSalt = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstBlockProofs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitmentReveal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCommitmentReveal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCommitmentReveal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstBlockProofs = append(m.FirstBlockProofs, ProofCommitment{})
			if err := m.FirstBlockProofs[len(m.FirstBlockProofs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondLeafHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitmentReveal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommitmentReveal
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommitmentReveal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecondLeafHash = append(m.SecondLeafHash[:0], dAtA[iNdEx:postIndex]...)
			if m.SecondLeafHash == nil {
				m.SecondLeafHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommitmentReveal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommitmentReveal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommitmentReveal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommitmentReveal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommitmentReveal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommitmentReveal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommitmentReveal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommitmentReveal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommitmentReveal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommitmentReveal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommitmentReveal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommitmentReveal = fmt.Errorf("proto: unexpected end of group")
)
