// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/verification/v1/proof_commitment.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProofCommitment records a validator's result for one proof position.
type ProofCommitment struct {
	ProofIndex   int64 `protobuf:"varint,1,opt,name=proof_index,json=proofIndex,proto3" json:"proof_index,omitempty"`
	IsProofValid bool  `protobuf:"varint,2,opt,name=is_proof_valid,json=isProofValid,proto3" json:"is_proof_valid,omitempty"`
}

func (m *ProofCommitment) Reset()         { *m = ProofCommitment{} }
func (m *ProofCommitment) String() string { return proto.CompactTextString(m) }
func (*ProofCommitment) ProtoMessage()    {}
func (*ProofCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_95511a3800184d2a, []int{0}
}
func (m *ProofCommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofCommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofCommitment.Merge(m, src)
}
func (m *ProofCommitment) XXX_Size() int {
	return m.Size()
}
func (m *ProofCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_ProofCommitment proto.InternalMessageInfo

func (m *ProofCommitment) GetProofIndex() int64 {
	if m != nil {
		return m.ProofIndex
	}
	return 0
}

func (m *ProofCommitment) GetIsProofValid() bool {
	if m != nil {
		return m.IsProofValid
	}
	return false
}

func init() {
	proto.RegisterType((*ProofCommitment)(nil), "pulsarchain.verification.v1.ProofCommitment")
}

func init() {
	proto.RegisterFile("pulsarchain/verification/v1/proof_commitment.proto", fileDescriptor_95511a3800184d2a)
}

var fileDescriptor_95511a3800184d2a = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x2a, 0x28, 0xcd, 0x29,
	0x4e, 0x2c, 0x4a, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0x4b, 0x2d, 0xca, 0x4c, 0xcb, 0x4c, 0x4e,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0x33, 0xd4, 0x2f, 0x28, 0xca, 0xcf, 0x4f, 0x8b, 0x4f, 0xce,
	0xcf, 0xcd, 0xcd, 0x2c, 0xc9, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92,
	0x46, 0xd2, 0xa3, 0x87, 0xac, 0x47, 0xaf, 0xcc, 0x50, 0x4a, 0x30, 0x31, 0x37, 0x33, 0x2f, 0x5f,
	0x1f, 0x4c, 0x42, 0xd4, 0x4b, 0x89, 0xa4, 0xe7, 0xa7, 0xe7, 0x83, 0x99, 0xfa, 0x20, 0x16, 0x44,
	0x54, 0x29, 0x82, 0x8b, 0x3f, 0x00, 0x64, 0xbe, 0x33, 0xdc, 0x78, 0x21, 0x79, 0x2e, 0x6e, 0x88,
	0x95, 0x99, 0x79, 0x29, 0xa9, 0x15, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x5c, 0x60, 0x21,
	0x4f, 0x90, 0x88, 0x90, 0x0a, 0x17, 0x5f, 0x66, 0x71, 0x3c, 0x44, 0x4d, 0x59, 0x62, 0x4e, 0x66,
	0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x4f, 0x66, 0x31, 0xd8, 0xac, 0x30, 0x90, 0x98,
	0x53, 0xe0, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1,
	0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x99, 0xa7, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xe7, 0xe5, 0xa7, 0xa4, 0x1a, 0x1a, 0x18, 0xea,
	0x66, 0xe6, 0xeb, 0x43, 0xfc, 0xa3, 0x0b, 0x09, 0x84, 0x0a, 0xd4, 0x60, 0x28, 0xa9, 0x2c, 0x48,
	0x2d, 0x4e, 0x62, 0x03, 0xbb, 0xd9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xec, 0x8f, 0xbe, 0x23,
	0x2f, 0x01, 0x00, 0x00,
}

func (m *ProofCommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofCommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofCommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsProofValid {
		i--
		if m.IsProofValid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.ProofIndex != 0 {
		i = encodeVarintProofCommitment(dAtA, i, uint64(m.ProofIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintProofCommitment(dAtA []byte, offset int, v uint64) int {
	offset -= sovProofCommitment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProofCommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProofIndex != 0 {
		n += 1 + sovProofCommitment(uint64(m.ProofIndex))
	}
	if m.IsProofValid {
		n += 2
	}
	return n
}

func sovProofCommitment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProofCommitment(x uint64) (n int) {
	return sovProofCommitment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProofCommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProofCommitment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofCommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofCommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofIndex", wireType)
			}
			m.ProofIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProofCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsProofValid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProofCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsProofValid = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipProofCommitment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProofCommitment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProofCommitment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProofCommitment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProofCommitment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProofCommitment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProofCommitment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProofCommitment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProofCommitment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProofCommitment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProofCommitment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProofCommitment = fmt.Errorf("proto: unexpected end of group")
)
