// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/verification/v1/types.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProofType selects the verifier family. The exact statement and circuit are
// bound separately by the public-input and verification-key hashes.
type ProofType int32

const (
	// PROOF_TYPE_UNSPECIFIED is invalid for proof submission.
	ProofType_PROOF_TYPE_UNSPECIFIED ProofType = 0
	// PROOF_TYPE_MINA_PICKLES selects Mina's Pickles proof system.
	ProofType_PROOF_TYPE_MINA_PICKLES ProofType = 1
	// PROOF_TYPE_NOIR_BARRETENBERG selects Noir proofs using Barretenberg.
	ProofType_PROOF_TYPE_NOIR_BARRETENBERG ProofType = 2
)

var ProofType_name = map[int32]string{
	0: "PROOF_TYPE_UNSPECIFIED",
	1: "PROOF_TYPE_MINA_PICKLES",
	2: "PROOF_TYPE_NOIR_BARRETENBERG",
}

var ProofType_value = map[string]int32{
	"PROOF_TYPE_UNSPECIFIED":       0,
	"PROOF_TYPE_MINA_PICKLES":      1,
	"PROOF_TYPE_NOIR_BARRETENBERG": 2,
}

func (x ProofType) String() string {
	return proto.EnumName(ProofType_name, int32(x))
}

func (ProofType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{0}
}

// VoteState tracks a validator's effective vote.
type VoteState int32

const (
	// VOTE_STATE_NONE means the validator has not voted.
	VoteState_VOTE_STATE_NONE VoteState = 0
	// VOTE_STATE_TRUE is an effective valid vote.
	VoteState_VOTE_STATE_TRUE VoteState = 1
	// VOTE_STATE_FALSE is an effective invalid vote.
	VoteState_VOTE_STATE_FALSE VoteState = 2
	// VOTE_STATE_EQUIVOCATED excludes conflicting votes from the tally.
	VoteState_VOTE_STATE_EQUIVOCATED VoteState = 3
)

var VoteState_name = map[int32]string{
	0: "VOTE_STATE_NONE",
	1: "VOTE_STATE_TRUE",
	2: "VOTE_STATE_FALSE",
	3: "VOTE_STATE_EQUIVOCATED",
}

var VoteState_value = map[string]int32{
	"VOTE_STATE_NONE":        0,
	"VOTE_STATE_TRUE":        1,
	"VOTE_STATE_FALSE":       2,
	"VOTE_STATE_EQUIVOCATED": 3,
}

func (x VoteState) String() string {
	return proto.EnumName(VoteState_name, int32(x))
}

func (VoteState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{1}
}

// ProofStatus is the finalized verification outcome.
type ProofStatus int32

const (
	// PROOF_STATUS_PENDING is the non-finalized status.
	ProofStatus_PROOF_STATUS_PENDING ProofStatus = 0
	// PROOF_STATUS_VALID means valid voting power exceeded two thirds.
	ProofStatus_PROOF_STATUS_VALID ProofStatus = 1
	// PROOF_STATUS_INVALID means invalid voting power exceeded two thirds.
	ProofStatus_PROOF_STATUS_INVALID ProofStatus = 2
	// PROOF_STATUS_INCONCLUSIVE means neither side reached threshold.
	ProofStatus_PROOF_STATUS_INCONCLUSIVE ProofStatus = 3
)

var ProofStatus_name = map[int32]string{
	0: "PROOF_STATUS_PENDING",
	1: "PROOF_STATUS_VALID",
	2: "PROOF_STATUS_INVALID",
	3: "PROOF_STATUS_INCONCLUSIVE",
}

var ProofStatus_value = map[string]int32{
	"PROOF_STATUS_PENDING":      0,
	"PROOF_STATUS_VALID":        1,
	"PROOF_STATUS_INVALID":      2,
	"PROOF_STATUS_INCONCLUSIVE": 3,
}

func (x ProofStatus) String() string {
	return proto.EnumName(ProofStatus_name, int32(x))
}

func (ProofStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{2}
}

// LeafRevealMode selects a full value or hash-only revelation.
type LeafRevealMode int32

const (
	// LEAF_REVEAL_MODE_UNSPECIFIED is invalid.
	LeafRevealMode_LEAF_REVEAL_MODE_UNSPECIFIED LeafRevealMode = 0
	// LEAF_REVEAL_MODE_HASH_ONLY reveals only the committed leaf hash.
	LeafRevealMode_LEAF_REVEAL_MODE_HASH_ONLY LeafRevealMode = 1
	// LEAF_REVEAL_MODE_VALUE reveals salt and canonical votes.
	LeafRevealMode_LEAF_REVEAL_MODE_VALUE LeafRevealMode = 2
)

var LeafRevealMode_name = map[int32]string{
	0: "LEAF_REVEAL_MODE_UNSPECIFIED",
	1: "LEAF_REVEAL_MODE_HASH_ONLY",
	2: "LEAF_REVEAL_MODE_VALUE",
}

var LeafRevealMode_value = map[string]int32{
	"LEAF_REVEAL_MODE_UNSPECIFIED": 0,
	"LEAF_REVEAL_MODE_HASH_ONLY":   1,
	"LEAF_REVEAL_MODE_VALUE":       2,
}

func (x LeafRevealMode) String() string {
	return proto.EnumName(LeafRevealMode_name, int32(x))
}

func (LeafRevealMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{3}
}

// ProofKey identifies a proof by absolute block height and in-block index.
type ProofKey struct {
	SubmissionHeight uint64 `protobuf:"varint,1,opt,name=submission_height,json=submissionHeight,proto3" json:"submission_height,omitempty"`
	IndexInBlock     uint32 `protobuf:"varint,2,opt,name=index_in_block,json=indexInBlock,proto3" json:"index_in_block,omitempty"`
}

func (m *ProofKey) Reset()         { *m = ProofKey{} }
func (m *ProofKey) String() string { return proto.CompactTextString(m) }
func (*ProofKey) ProtoMessage()    {}
func (*ProofKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{0}
}
func (m *ProofKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofKey.Merge(m, src)
}
func (m *ProofKey) XXX_Size() int {
	return m.Size()
}
func (m *ProofKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofKey.DiscardUnknown(m)
}

var xxx_messageInfo_ProofKey proto.InternalMessageInfo

func (m *ProofKey) GetSubmissionHeight() uint64 {
	if m != nil {
		return m.SubmissionHeight
	}
	return 0
}

func (m *ProofKey) GetIndexInBlock() uint32 {
	if m != nil {
		return m.IndexInBlock
	}
	return 0
}

// ProofRecord stores the complete descriptor and its chain-derived identity.
type ProofRecord struct {
	ProofHash           []byte    `protobuf:"bytes,1,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	ProofType           ProofType `protobuf:"varint,2,opt,name=proof_type,json=proofType,proto3,enum=pulsarchain.verification.v1.ProofType" json:"proof_type,omitempty"`
	PublicInputsHash    []byte    `protobuf:"bytes,3,opt,name=public_inputs_hash,json=publicInputsHash,proto3" json:"public_inputs_hash,omitempty"`
	VerificationKeyHash []byte    `protobuf:"bytes,4,opt,name=verification_key_hash,json=verificationKeyHash,proto3" json:"verification_key_hash,omitempty"`
	VerificationId      []byte    `protobuf:"bytes,5,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
}

func (m *ProofRecord) Reset()         { *m = ProofRecord{} }
func (m *ProofRecord) String() string { return proto.CompactTextString(m) }
func (*ProofRecord) ProtoMessage()    {}
func (*ProofRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{1}
}
func (m *ProofRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofRecord.Merge(m, src)
}
func (m *ProofRecord) XXX_Size() int {
	return m.Size()
}
func (m *ProofRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ProofRecord proto.InternalMessageInfo

func (m *ProofRecord) GetProofHash() []byte {
	if m != nil {
		return m.ProofHash
	}
	return nil
}

func (m *ProofRecord) GetProofType() ProofType {
	if m != nil {
		return m.ProofType
	}
	return ProofType_PROOF_TYPE_UNSPECIFIED
}

func (m *ProofRecord) GetPublicInputsHash() []byte {
	if m != nil {
		return m.PublicInputsHash
	}
	return nil
}

func (m *ProofRecord) GetVerificationKeyHash() []byte {
	if m != nil {
		return m.VerificationKeyHash
	}
	return nil
}

func (m *ProofRecord) GetVerificationId() []byte {
	if m != nil {
		return m.VerificationId
	}
	return nil
}

// CommitmentRecord stores a validator commitment root.
type CommitmentRecord struct {
	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (m *CommitmentRecord) Reset()         { *m = CommitmentRecord{} }
func (m *CommitmentRecord) String() string { return proto.CompactTextString(m) }
func (*CommitmentRecord) ProtoMessage()    {}
func (*CommitmentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{2}
}
func (m *CommitmentRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommitmentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommitmentRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommitmentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitmentRecord.Merge(m, src)
}
func (m *CommitmentRecord) XXX_Size() int {
	return m.Size()
}
func (m *CommitmentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitmentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CommitmentRecord proto.InternalMessageInfo

func (m *CommitmentRecord) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

// ProofVote records a result for one proof index.
type ProofVote struct {
	IndexInBlock uint32 `protobuf:"varint,1,opt,name=index_in_block,json=indexInBlock,proto3" json:"index_in_block,omitempty"`
	Result       bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *ProofVote) Reset()         { *m = ProofVote{} }
func (m *ProofVote) String() string { return proto.CompactTextString(m) }
func (*ProofVote) ProtoMessage()    {}
func (*ProofVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{3}
}
func (m *ProofVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofVote.Merge(m, src)
}
func (m *ProofVote) XXX_Size() int {
	return m.Size()
}
func (m *ProofVote) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofVote.DiscardUnknown(m)
}

var xxx_messageInfo_ProofVote proto.InternalMessageInfo

func (m *ProofVote) GetIndexInBlock() uint32 {
	if m != nil {
		return m.IndexInBlock
	}
	return 0
}

func (m *ProofVote) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// ProofTally stores the historical consensus power behind effective votes.
type ProofTally struct {
	ValidVotingPower   int64 `protobuf:"varint,1,opt,name=valid_voting_power,json=validVotingPower,proto3" json:"valid_voting_power,omitempty"`
	InvalidVotingPower int64 `protobuf:"varint,2,opt,name=invalid_voting_power,json=invalidVotingPower,proto3" json:"invalid_voting_power,omitempty"`
}

func (m *ProofTally) Reset()         { *m = ProofTally{} }
func (m *ProofTally) String() string { return proto.CompactTextString(m) }
func (*ProofTally) ProtoMessage()    {}
func (*ProofTally) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{4}
}
func (m *ProofTally) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofTally) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofTally.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofTally) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofTally.Merge(m, src)
}
func (m *ProofTally) XXX_Size() int {
	return m.Size()
}
func (m *ProofTally) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofTally.DiscardUnknown(m)
}

var xxx_messageInfo_ProofTally proto.InternalMessageInfo

func (m *ProofTally) GetValidVotingPower() int64 {
	if m != nil {
		return m.ValidVotingPower
	}
	return 0
}

func (m *ProofTally) GetInvalidVotingPower() int64 {
	if m != nil {
		return m.InvalidVotingPower
	}
	return 0
}

// FinalProofResult stores an immutable finalized proof outcome.
type FinalProofResult struct {
	ProofHash            []byte      `protobuf:"bytes,1,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	ProofType            ProofType   `protobuf:"varint,2,opt,name=proof_type,json=proofType,proto3,enum=pulsarchain.verification.v1.ProofType" json:"proof_type,omitempty"`
	Status               ProofStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pulsarchain.verification.v1.ProofStatus" json:"status,omitempty"`
	ValidVotingPower     int64       `protobuf:"varint,4,opt,name=valid_voting_power,json=validVotingPower,proto3" json:"valid_voting_power,omitempty"`
	InvalidVotingPower   int64       `protobuf:"varint,5,opt,name=invalid_voting_power,json=invalidVotingPower,proto3" json:"invalid_voting_power,omitempty"`
	TotalVotingPower     int64       `protobuf:"varint,6,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	VotingPowerThreshold int64       `protobuf:"varint,7,opt,name=voting_power_threshold,json=votingPowerThreshold,proto3" json:"voting_power_threshold,omitempty"`
	SubmissionHeight     uint64      `protobuf:"varint,8,opt,name=submission_height,json=submissionHeight,proto3" json:"submission_height,omitempty"`
	FinalizedHeight      uint64      `protobuf:"varint,9,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"`
	PublicInputsHash     []byte      `protobuf:"bytes,10,opt,name=public_inputs_hash,json=publicInputsHash,proto3" json:"public_inputs_hash,omitempty"`
	VerificationKeyHash  []byte      `protobuf:"bytes,11,opt,name=verification_key_hash,json=verificationKeyHash,proto3" json:"verification_key_hash,omitempty"`
	VerificationId       []byte      `protobuf:"bytes,12,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
}

func (m *FinalProofResult) Reset()         { *m = FinalProofResult{} }
func (m *FinalProofResult) String() string { return proto.CompactTextString(m) }
func (*FinalProofResult) ProtoMessage()    {}
func (*FinalProofResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{5}
}
func (m *FinalProofResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FinalProofResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FinalProofResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FinalProofResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalProofResult.Merge(m, src)
}
func (m *FinalProofResult) XXX_Size() int {
	return m.Size()
}
func (m *FinalProofResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalProofResult.DiscardUnknown(m)
}

var xxx_messageInfo_FinalProofResult proto.InternalMessageInfo

func (m *FinalProofResult) GetProofHash() []byte {
	if m != nil {
		return m.ProofHash
	}
	return nil
}

func (m *FinalProofResult) GetProofType() ProofType {
	if m != nil {
		return m.ProofType
	}
	return ProofType_PROOF_TYPE_UNSPECIFIED
}

func (m *FinalProofResult) GetStatus() ProofStatus {
	if m != nil {
		return m.Status
	}
	return ProofStatus_PROOF_STATUS_PENDING
}

func (m *FinalProofResult) GetValidVotingPower() int64 {
	if m != nil {
		return m.ValidVotingPower
	}
	return 0
}

func (m *FinalProofResult) GetInvalidVotingPower() int64 {
	if m != nil {
		return m.InvalidVotingPower
	}
	return 0
}

func (m *FinalProofResult) GetTotalVotingPower() int64 {
	if m != nil {
		return m.TotalVotingPower
	}
	return 0
}

func (m *FinalProofResult) GetVotingPowerThreshold() int64 {
	if m != nil {
		return m.VotingPowerThreshold
	}
	return 0
}

func (m *FinalProofResult) GetSubmissionHeight() uint64 {
	if m != nil {
		return m.SubmissionHeight
	}
	return 0
}

func (m *FinalProofResult) GetFinalizedHeight() uint64 {
	if m != nil {
		return m.FinalizedHeight
	}
	return 0
}

func (m *FinalProofResult) GetPublicInputsHash() []byte {
	if m != nil {
		return m.PublicInputsHash
	}
	return nil
}

func (m *FinalProofResult) GetVerificationKeyHash() []byte {
	if m != nil {
		return m.VerificationKeyHash
	}
	return nil
}

func (m *FinalProofResult) GetVerificationId() []byte {
	if m != nil {
		return m.VerificationId
	}
	return nil
}

// RevealedLeaf contains a salt and canonical vote list.
type RevealedLeaf struct {
	Salt  []byte      `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	Votes []ProofVote `protobuf:"bytes,2,rep,name=votes,proto3" json:"votes"`
}

func (m *RevealedLeaf) Reset()         { *m = RevealedLeaf{} }
func (m *RevealedLeaf) String() string { return proto.CompactTextString(m) }
func (*RevealedLeaf) ProtoMessage()    {}
func (*RevealedLeaf) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{6}
}
func (m *RevealedLeaf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RevealedLeaf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RevealedLeaf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RevealedLeaf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevealedLeaf.Merge(m, src)
}
func (m *RevealedLeaf) XXX_Size() int {
	return m.Size()
}
func (m *RevealedLeaf) XXX_DiscardUnknown() {
	xxx_messageInfo_RevealedLeaf.DiscardUnknown(m)
}

var xxx_messageInfo_RevealedLeaf proto.InternalMessageInfo

func (m *RevealedLeaf) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *RevealedLeaf) GetVotes() []ProofVote {
	if m != nil {
		return m.Votes
	}
	return nil
}

// LeafRevelation opens or references one commitment leaf.
type LeafRevelation struct {
	Mode LeafRevealMode `protobuf:"varint,1,opt,name=mode,proto3,enum=pulsarchain.verification.v1.LeafRevealMode" json:"mode,omitempty"`
	// payload must match mode.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*LeafRevelation_LeafHash
	//	*LeafRevelation_Value
	Payload isLeafRevelation_Payload `protobuf_oneof:"payload"`
}

func (m *LeafRevelation) Reset()         { *m = LeafRevelation{} }
func (m *LeafRevelation) String() string { return proto.CompactTextString(m) }
func (*LeafRevelation) ProtoMessage()    {}
func (*LeafRevelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{7}
}
func (m *LeafRevelation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LeafRevelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LeafRevelation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LeafRevelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeafRevelation.Merge(m, src)
}
func (m *LeafRevelation) XXX_Size() int {
	return m.Size()
}
func (m *LeafRevelation) XXX_DiscardUnknown() {
	xxx_messageInfo_LeafRevelation.DiscardUnknown(m)
}

var xxx_messageInfo_LeafRevelation proto.InternalMessageInfo

type isLeafRevelation_Payload interface {
	isLeafRevelation_Payload()
	MarshalTo([]byte) (int, error)
	Size() int
}

type LeafRevelation_LeafHash struct {
	LeafHash []byte `protobuf:"bytes,2,opt,name=leaf_hash,json=leafHash,proto3,oneof" json:"leaf_hash,omitempty"`
}
type LeafRevelation_Value struct {
	Value *RevealedLeaf `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (*LeafRevelation_LeafHash) isLeafRevelation_Payload() {}
func (*LeafRevelation_Value) isLeafRevelation_Payload()    {}

func (m *LeafRevelation) GetPayload() isLeafRevelation_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *LeafRevelation) GetMode() LeafRevealMode {
	if m != nil {
		return m.Mode
	}
	return LeafRevealMode_LEAF_REVEAL_MODE_UNSPECIFIED
}

func (m *LeafRevelation) GetLeafHash() []byte {
	if x, ok := m.GetPayload().(*LeafRevelation_LeafHash); ok {
		return x.LeafHash
	}
	return nil
}

func (m *LeafRevelation) GetValue() *RevealedLeaf {
	if x, ok := m.GetPayload().(*LeafRevelation_Value); ok {
		return x.Value
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LeafRevelation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LeafRevelation_LeafHash)(nil),
		(*LeafRevelation_Value)(nil),
	}
}

// CommitmentRevelation opens the left and right commitment leaves.
type CommitmentRevelation struct {
	CommitmentHeight uint64         `protobuf:"varint,1,opt,name=commitment_height,json=commitmentHeight,proto3" json:"commitment_height,omitempty"`
	Left             LeafRevelation `protobuf:"bytes,2,opt,name=left,proto3" json:"left"`
	Right            LeafRevelation `protobuf:"bytes,3,opt,name=right,proto3" json:"right"`
}

func (m *CommitmentRevelation) Reset()         { *m = CommitmentRevelation{} }
func (m *CommitmentRevelation) String() string { return proto.CompactTextString(m) }
func (*CommitmentRevelation) ProtoMessage()    {}
func (*CommitmentRevelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{8}
}
func (m *CommitmentRevelation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommitmentRevelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommitmentRevelation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommitmentRevelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitmentRevelation.Merge(m, src)
}
func (m *CommitmentRevelation) XXX_Size() int {
	return m.Size()
}
func (m *CommitmentRevelation) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitmentRevelation.DiscardUnknown(m)
}

var xxx_messageInfo_CommitmentRevelation proto.InternalMessageInfo

func (m *CommitmentRevelation) GetCommitmentHeight() uint64 {
	if m != nil {
		return m.CommitmentHeight
	}
	return 0
}

func (m *CommitmentRevelation) GetLeft() LeafRevelation {
	if m != nil {
		return m.Left
	}
	return LeafRevelation{}
}

func (m *CommitmentRevelation) GetRight() LeafRevelation {
	if m != nil {
		return m.Right
	}
	return LeafRevelation{}
}

// CommitmentEntry is a query representation of a retained commitment.
type CommitmentEntry struct {
	Validator        string           `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	CommitmentHeight uint64           `protobuf:"varint,2,opt,name=commitment_height,json=commitmentHeight,proto3" json:"commitment_height,omitempty"`
	Commitment       CommitmentRecord `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment"`
}

func (m *CommitmentEntry) Reset()         { *m = CommitmentEntry{} }
func (m *CommitmentEntry) String() string { return proto.CompactTextString(m) }
func (*CommitmentEntry) ProtoMessage()    {}
func (*CommitmentEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{9}
}
func (m *CommitmentEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommitmentEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommitmentEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommitmentEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitmentEntry.Merge(m, src)
}
func (m *CommitmentEntry) XXX_Size() int {
	return m.Size()
}
func (m *CommitmentEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitmentEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CommitmentEntry proto.InternalMessageInfo

func (m *CommitmentEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *CommitmentEntry) GetCommitmentHeight() uint64 {
	if m != nil {
		return m.CommitmentHeight
	}
	return 0
}

func (m *CommitmentEntry) GetCommitment() CommitmentRecord {
	if m != nil {
		return m.Commitment
	}
	return CommitmentRecord{}
}

// VerificationVoteEntry is a query representation of an effective vote.
type VerificationVoteEntry struct {
	ProofKey  ProofKey  `protobuf:"bytes,1,opt,name=proof_key,json=proofKey,proto3" json:"proof_key"`
	Validator string    `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	State     VoteState `protobuf:"varint,3,opt,name=state,proto3,enum=pulsarchain.verification.v1.VoteState" json:"state,omitempty"`
}

func (m *VerificationVoteEntry) Reset()         { *m = VerificationVoteEntry{} }
func (m *VerificationVoteEntry) String() string { return proto.CompactTextString(m) }
func (*VerificationVoteEntry) ProtoMessage()    {}
func (*VerificationVoteEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7b78249095f18f, []int{10}
}
func (m *VerificationVoteEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerificationVoteEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerificationVoteEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerificationVoteEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationVoteEntry.Merge(m, src)
}
func (m *VerificationVoteEntry) XXX_Size() int {
	return m.Size()
}
func (m *VerificationVoteEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationVoteEntry.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationVoteEntry proto.InternalMessageInfo

func (m *VerificationVoteEntry) GetProofKey() ProofKey {
	if m != nil {
		return m.ProofKey
	}
	return ProofKey{}
}

func (m *VerificationVoteEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *VerificationVoteEntry) GetState() VoteState {
	if m != nil {
		return m.State
	}
	return VoteState_VOTE_STATE_NONE
}

func init() {
	proto.RegisterEnum("pulsarchain.verification.v1.ProofType", ProofType_name, ProofType_value)
	proto.RegisterEnum("pulsarchain.verification.v1.VoteState", VoteState_name, VoteState_value)
	proto.RegisterEnum("pulsarchain.verification.v1.ProofStatus", ProofStatus_name, ProofStatus_value)
	proto.RegisterEnum("pulsarchain.verification.v1.LeafRevealMode", LeafRevealMode_name, LeafRevealMode_value)
	proto.RegisterType((*ProofKey)(nil), "pulsarchain.verification.v1.ProofKey")
	proto.RegisterType((*ProofRecord)(nil), "pulsarchain.verification.v1.ProofRecord")
	proto.RegisterType((*CommitmentRecord)(nil), "pulsarchain.verification.v1.CommitmentRecord")
	proto.RegisterType((*ProofVote)(nil), "pulsarchain.verification.v1.ProofVote")
	proto.RegisterType((*ProofTally)(nil), "pulsarchain.verification.v1.ProofTally")
	proto.RegisterType((*FinalProofResult)(nil), "pulsarchain.verification.v1.FinalProofResult")
	proto.RegisterType((*RevealedLeaf)(nil), "pulsarchain.verification.v1.RevealedLeaf")
	proto.RegisterType((*LeafRevelation)(nil), "pulsarchain.verification.v1.LeafRevelation")
	proto.RegisterType((*CommitmentRevelation)(nil), "pulsarchain.verification.v1.CommitmentRevelation")
	proto.RegisterType((*CommitmentEntry)(nil), "pulsarchain.verification.v1.CommitmentEntry")
	proto.RegisterType((*VerificationVoteEntry)(nil), "pulsarchain.verification.v1.VerificationVoteEntry")
}

func init() {
	proto.RegisterFile("pulsarchain/verification/v1/types.proto", fileDescriptor_8a7b78249095f18f)
}

var fileDescriptor_8a7b78249095f18f = []byte{
	// 1140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5d, 0x6f, 0x1a, 0x47,
	0x17, 0x66, 0xf9, 0x70, 0xcc, 0xc1, 0x2f, 0xde, 0x4c, 0x88, 0x5f, 0xea, 0x24, 0xd4, 0x45, 0x6d,
	0xe2, 0x38, 0x35, 0xc4, 0xb4, 0x52, 0x6f, 0x2a, 0xb5, 0x80, 0xc7, 0x66, 0x65, 0x0c, 0x64, 0xf9,
	0x90, 0x52, 0xa9, 0x5a, 0xad, 0xd9, 0x01, 0xb6, 0x59, 0x76, 0x10, 0xbb, 0x50, 0xd3, 0x3f, 0xd1,
	0xfe, 0x94, 0xb6, 0xf7, 0xbd, 0xcf, 0x65, 0xa4, 0xde, 0xf4, 0xaa, 0x6a, 0xed, 0x8b, 0xfe, 0x8b,
	0xaa, 0x9a, 0x99, 0xc5, 0x2c, 0x18, 0x93, 0xb8, 0x17, 0xbd, 0x41, 0xc3, 0x79, 0x9e, 0xf3, 0x31,
	0xcf, 0xcc, 0x39, 0xb3, 0xf0, 0x64, 0x30, 0xb2, 0x1c, 0x7d, 0xd8, 0xee, 0xe9, 0xa6, 0x9d, 0x1d,
	0x93, 0xa1, 0xd9, 0x31, 0xdb, 0xba, 0x6b, 0x52, 0x3b, 0x3b, 0x3e, 0xc8, 0xba, 0x93, 0x01, 0x71,
	0x32, 0x83, 0x21, 0x75, 0x29, 0x7a, 0xe0, 0x23, 0x66, 0xfc, 0xc4, 0xcc, 0xf8, 0x60, 0xfb, 0xae,
	0xde, 0x37, 0x6d, 0x9a, 0xe5, 0xbf, 0x82, 0xbf, 0x9d, 0xe8, 0xd2, 0x2e, 0xe5, 0xcb, 0x2c, 0x5b,
	0x09, 0x6b, 0xfa, 0x6b, 0x58, 0xaf, 0x0d, 0x29, 0xed, 0x9c, 0x90, 0x09, 0x7a, 0x06, 0x77, 0x9d,
	0xd1, 0x59, 0xdf, 0x74, 0x1c, 0x93, 0xda, 0x5a, 0x8f, 0x98, 0xdd, 0x9e, 0x9b, 0x94, 0x76, 0xa4,
	0xdd, 0xb0, 0x2a, 0xcf, 0x80, 0x12, 0xb7, 0xa3, 0x0f, 0x21, 0x6e, 0xda, 0x06, 0x39, 0xd7, 0x4c,
	0x5b, 0x3b, 0xb3, 0x68, 0xfb, 0x55, 0x32, 0xb8, 0x23, 0xed, 0xfe, 0x4f, 0xdd, 0xe0, 0x56, 0xc5,
	0x2e, 0x30, 0x5b, 0xfa, 0x6f, 0x09, 0x62, 0x3c, 0xbe, 0x4a, 0xda, 0x74, 0x68, 0xa0, 0x47, 0x00,
	0x03, 0xf6, 0x57, 0xeb, 0xe9, 0x4e, 0x8f, 0xc7, 0xde, 0x50, 0xa3, 0xdc, 0x52, 0xd2, 0x9d, 0x1e,
	0xc2, 0x53, 0x98, 0x6d, 0x94, 0x07, 0x8c, 0xe7, 0x1e, 0x67, 0x56, 0x6c, 0x34, 0xc3, 0x83, 0x37,
	0x26, 0x03, 0xe2, 0x85, 0x61, 0x4b, 0xf4, 0x31, 0xa0, 0xc1, 0xe8, 0xcc, 0x32, 0xdb, 0x9a, 0x69,
	0x0f, 0x46, 0xae, 0x23, 0xb2, 0x85, 0x78, 0x36, 0x59, 0x20, 0x0a, 0x07, 0x78, 0xd2, 0x1c, 0xdc,
	0xf7, 0x47, 0xd5, 0x5e, 0x91, 0x89, 0x70, 0x08, 0x73, 0x87, 0x7b, 0x7e, 0xf0, 0x84, 0x4c, 0xb8,
	0xcf, 0x13, 0xd8, 0x9c, 0xf3, 0x31, 0x8d, 0x64, 0x84, 0xb3, 0xe3, 0x7e, 0xb3, 0x62, 0xa4, 0x73,
	0x20, 0x17, 0x69, 0xbf, 0x6f, 0xba, 0x7d, 0x62, 0xbb, 0x9e, 0x08, 0x29, 0x80, 0xf6, 0x95, 0xcd,
	0x13, 0xc1, 0x67, 0x49, 0x2b, 0x10, 0xe5, 0xdb, 0x6a, 0x51, 0x97, 0x2c, 0xd1, 0x59, 0xba, 0xae,
	0x33, 0xda, 0x82, 0xb5, 0x21, 0x71, 0x46, 0x96, 0xcb, 0x45, 0x5b, 0x57, 0xbd, 0x7f, 0x69, 0x0b,
	0x40, 0x28, 0xa4, 0x5b, 0xd6, 0x84, 0xe9, 0x32, 0xd6, 0x2d, 0xd3, 0xd0, 0xc6, 0xd4, 0x35, 0xed,
	0xae, 0x36, 0xa0, 0xdf, 0x92, 0x21, 0x8f, 0x17, 0x52, 0x65, 0x8e, 0xb4, 0x38, 0x50, 0x63, 0x76,
	0xf4, 0x1c, 0x12, 0xa6, 0xbd, 0x84, 0x1f, 0xe4, 0x7c, 0xe4, 0x61, 0x3e, 0x8f, 0xf4, 0x9f, 0x61,
	0x90, 0x8f, 0x4c, 0x5b, 0xb7, 0xbc, 0x23, 0x67, 0x25, 0xfc, 0x47, 0x47, 0xfe, 0x25, 0xac, 0x39,
	0xae, 0xee, 0x8e, 0x1c, 0x7e, 0xcc, 0xf1, 0xdc, 0xee, 0xdb, 0x43, 0xd4, 0x39, 0x5f, 0xf5, 0xfc,
	0x6e, 0x10, 0x27, 0x7c, 0x4b, 0x71, 0x22, 0x37, 0x89, 0xc3, 0xe2, 0xbb, 0xd4, 0xd5, 0xad, 0x79,
	0xfe, 0x9a, 0x88, 0xcf, 0x11, 0x3f, 0xfb, 0x53, 0xd8, 0xf2, 0xf3, 0x34, 0xb7, 0x37, 0x24, 0x4e,
	0x8f, 0x5a, 0x46, 0xf2, 0x0e, 0xf7, 0x48, 0x8c, 0x67, 0xe4, 0xc6, 0x14, 0x5b, 0xde, 0xc1, 0xeb,
	0x37, 0x74, 0xf0, 0x53, 0x90, 0x3b, 0xec, 0xb0, 0xcc, 0xef, 0x88, 0x31, 0xe5, 0x46, 0x39, 0x77,
	0xf3, 0xca, 0xee, 0x51, 0x97, 0x37, 0x14, 0xdc, 0xb6, 0xa1, 0x62, 0xb7, 0x6a, 0xa8, 0x8d, 0xa5,
	0x0d, 0xd5, 0x81, 0x0d, 0x95, 0x8c, 0x89, 0x6e, 0x11, 0xa3, 0x4c, 0xf4, 0x0e, 0x42, 0x10, 0x76,
	0x74, 0x6b, 0xda, 0x46, 0x7c, 0x8d, 0x0a, 0x10, 0x19, 0x53, 0x97, 0x38, 0xc9, 0xe0, 0x4e, 0x68,
	0x37, 0xf6, 0x2e, 0xd7, 0x89, 0xb5, 0x5a, 0x21, 0xfc, 0xfa, 0xf7, 0xf7, 0x03, 0xaa, 0x70, 0x4d,
	0x7f, 0x1f, 0x84, 0x38, 0x4b, 0xc0, 0x92, 0x59, 0x9c, 0x8c, 0xbe, 0x80, 0x70, 0x9f, 0x1a, 0x84,
	0xa7, 0x8a, 0xe7, 0x9e, 0xad, 0x8c, 0x3a, 0x75, 0xd5, 0xad, 0x53, 0x6a, 0x10, 0x95, 0x3b, 0x22,
	0x0c, 0x51, 0x8b, 0xe8, 0x5e, 0x27, 0xb0, 0xab, 0xbe, 0x51, 0x78, 0xfc, 0xf3, 0x5f, 0x3f, 0xee,
	0x7d, 0x70, 0xe3, 0xcc, 0x67, 0x61, 0x98, 0x3e, 0xa5, 0x80, 0xba, 0x6e, 0x79, 0x6b, 0xf4, 0x0d,
	0x44, 0xc6, 0xba, 0x35, 0x22, 0xfc, 0xaa, 0xc7, 0x72, 0x4f, 0x57, 0x16, 0xe2, 0x17, 0xab, 0xf0,
	0x84, 0x65, 0x4b, 0xaf, 0xcc, 0xd6, 0x62, 0x91, 0x4b, 0x4c, 0x06, 0xb6, 0x28, 0x44, 0xe1, 0xce,
	0x40, 0x9f, 0x58, 0x54, 0x37, 0xd2, 0xbf, 0x4a, 0x90, 0xf0, 0xcf, 0xb2, 0x2b, 0x5d, 0x9e, 0xc1,
	0xdd, 0xd9, 0xf4, 0x5a, 0x78, 0x37, 0x66, 0x80, 0x77, 0x95, 0x30, 0x84, 0x2d, 0xd2, 0x11, 0x73,
	0x2a, 0xf6, 0x8e, 0x22, 0x8a, 0x3c, 0xde, 0xf9, 0x70, 0x77, 0x74, 0x0c, 0x91, 0x21, 0xcf, 0x13,
	0xfa, 0xb7, 0x71, 0x84, 0x7f, 0xfa, 0x27, 0x09, 0x36, 0x67, 0xbb, 0xc2, 0xb6, 0x3b, 0x9c, 0xa0,
	0x87, 0x10, 0xe5, 0xed, 0xab, 0xbb, 0x54, 0x8c, 0xc7, 0xa8, 0x3a, 0x33, 0x2c, 0xdf, 0x6e, 0xf0,
	0x86, 0xed, 0xd6, 0xe7, 0x66, 0xbd, 0x28, 0x76, 0x7f, 0x65, 0xb1, 0x8b, 0xcf, 0x85, 0x57, 0xae,
	0xff, 0x81, 0xf8, 0x45, 0x82, 0xfb, 0x2d, 0x9f, 0x1b, 0xbb, 0xbd, 0xa2, 0xf2, 0x12, 0x88, 0x99,
	0xc8, 0x7a, 0x8e, 0x57, 0x1e, 0xcb, 0x7d, 0xf4, 0xf6, 0xdb, 0x7f, 0x42, 0x26, 0x5e, 0x96, 0xf5,
	0xc1, 0xf4, 0x63, 0x60, 0x4e, 0x83, 0xe0, 0xa2, 0x06, 0x9f, 0x43, 0x84, 0x8d, 0x4d, 0xe2, 0x4d,
	0xdb, 0xd5, 0x1d, 0xc6, 0xca, 0x63, 0xc3, 0x96, 0xa8, 0xc2, 0x69, 0xaf, 0xe3, 0x3d, 0x70, 0x7c,
	0x72, 0x6f, 0xc3, 0x56, 0x4d, 0xad, 0x56, 0x8f, 0xb4, 0xc6, 0xcb, 0x1a, 0xd6, 0x9a, 0x95, 0x7a,
	0x0d, 0x17, 0x95, 0x23, 0x05, 0x1f, 0xca, 0x01, 0xf4, 0x00, 0xfe, 0xef, 0xc3, 0x4e, 0x95, 0x4a,
	0x5e, 0xab, 0x29, 0xc5, 0x93, 0x32, 0xae, 0xcb, 0x12, 0xda, 0x81, 0x87, 0x3e, 0xb0, 0x52, 0x55,
	0x54, 0xad, 0x90, 0x57, 0x55, 0xdc, 0xc0, 0x95, 0x02, 0x56, 0x8f, 0xe5, 0xe0, 0x5e, 0x17, 0xa2,
	0x57, 0xb9, 0xd1, 0x3d, 0xd8, 0x6c, 0x55, 0x1b, 0x58, 0xab, 0x37, 0xf2, 0x0d, 0x46, 0xaf, 0x60,
	0x39, 0xb0, 0x60, 0x6c, 0xa8, 0x4d, 0x2c, 0x4b, 0x28, 0x01, 0xb2, 0xcf, 0x78, 0x94, 0x2f, 0xd7,
	0xb1, 0x1c, 0x64, 0x75, 0xfa, 0xac, 0xf8, 0x45, 0x53, 0x69, 0x55, 0x8b, 0xf9, 0x06, 0x3e, 0x94,
	0x43, 0x7b, 0xe7, 0xde, 0x57, 0x8e, 0x78, 0x52, 0x50, 0x12, 0x12, 0xa2, 0x32, 0xc6, 0x6d, 0xd6,
	0xb5, 0x1a, 0xae, 0x1c, 0x2a, 0x95, 0x63, 0x39, 0x80, 0xb6, 0x00, 0xcd, 0x21, 0xad, 0x7c, 0x59,
	0x39, 0x94, 0xa5, 0x6b, 0x1e, 0x4a, 0x45, 0x20, 0x41, 0xf4, 0x08, 0xde, 0x5b, 0x40, 0x8a, 0xd5,
	0x4a, 0xb1, 0xdc, 0xac, 0x2b, 0x2d, 0x2c, 0x87, 0xf6, 0xec, 0xd9, 0x94, 0x12, 0xa3, 0x86, 0xc9,
	0x52, 0xc6, 0xf9, 0x23, 0x4d, 0xc5, 0x2d, 0x9c, 0x2f, 0x6b, 0xa7, 0xd5, 0xc3, 0x45, 0x55, 0x53,
	0xb0, 0x7d, 0x8d, 0x51, 0xca, 0xd7, 0x4b, 0x5a, 0xb5, 0x52, 0x7e, 0x29, 0x4b, 0x6c, 0xa7, 0xd7,
	0xf0, 0x56, 0xbe, 0xdc, 0xc4, 0x72, 0xb0, 0xf0, 0xe2, 0xf5, 0x45, 0x4a, 0x7a, 0x73, 0x91, 0x92,
	0xfe, 0xb8, 0x48, 0x49, 0x3f, 0x5c, 0xa6, 0x02, 0x6f, 0x2e, 0x53, 0x81, 0xdf, 0x2e, 0x53, 0x81,
	0xaf, 0x3e, 0xeb, 0x9a, 0x6e, 0x6f, 0x74, 0x96, 0x69, 0xd3, 0x7e, 0xd6, 0xa6, 0x06, 0x39, 0x78,
	0x7e, 0xb0, 0x6f, 0xd2, 0xac, 0xb8, 0x18, 0xfb, 0x62, 0xda, 0x9c, 0xcf, 0xcf, 0x1b, 0xfe, 0x39,
	0x7b, 0xb6, 0xc6, 0xbf, 0x44, 0x3f, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xcc, 0x6a, 0x61,
	0xfa, 0x0a, 0x00, 0x00,
}

func (m *ProofKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IndexInBlock != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.IndexInBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.SubmissionHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SubmissionHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ProofRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerificationId) > 0 {
		i -= len(m.VerificationId)
		copy(dAtA[i:], m.VerificationId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VerificationId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.VerificationKeyHash) > 0 {
		i -= len(m.VerificationKeyHash)
		copy(dAtA[i:], m.VerificationKeyHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VerificationKeyHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PublicInputsHash) > 0 {
		i -= len(m.PublicInputsHash)
		copy(dAtA[i:], m.PublicInputsHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PublicInputsHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProofType != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ProofType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ProofHash) > 0 {
		i -= len(m.ProofHash)
		copy(dAtA[i:], m.ProofHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ProofHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CommitmentRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommitmentRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommitmentRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProofVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result {
		i--
		if m.Result {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.IndexInBlock != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.IndexInBlock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ProofTally) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofTally) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofTally) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InvalidVotingPower != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.InvalidVotingPower))
		i--
		dAtA[i] = 0x10
	}
	if m.ValidVotingPower != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ValidVotingPower))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FinalProofResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FinalProofResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FinalProofResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerificationId) > 0 {
		i -= len(m.VerificationId)
		copy(dAtA[i:], m.VerificationId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VerificationId)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.VerificationKeyHash) > 0 {
		i -= len(m.VerificationKeyHash)
		copy(dAtA[i:], m.VerificationKeyHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VerificationKeyHash)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.PublicInputsHash) > 0 {
		i -= len(m.PublicInputsHash)
		copy(dAtA[i:], m.PublicInputsHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PublicInputsHash)))
		i--
		dAtA[i] = 0x52
	}
	if m.FinalizedHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.FinalizedHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.SubmissionHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SubmissionHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.VotingPowerThreshold != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VotingPowerThreshold))
		i--
		dAtA[i] = 0x38
	}
	if m.TotalVotingPower != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TotalVotingPower))
		i--
		dAtA[i] = 0x30
	}
	if m.InvalidVotingPower != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.InvalidVotingPower))
		i--
		dAtA[i] = 0x28
	}
	if m.ValidVotingPower != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ValidVotingPower))
		i--
		dAtA[i] = 0x20
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if m.ProofType != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ProofType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ProofHash) > 0 {
		i -= len(m.ProofHash)
		copy(dAtA[i:], m.ProofHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ProofHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RevealedLeaf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RevealedLeaf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RevealedLeaf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Votes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LeafRevelation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LeafRevelation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeafRevelation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Payload != nil {
		{
			size := m.Payload.Size()
			i -= size
			if _, err := m.Payload.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Mode != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LeafRevelation_LeafHash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeafRevelation_LeafHash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.LeafHash != nil {
		i -= len(m.LeafHash)
		copy(dAtA[i:], m.LeafHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LeafHash)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *LeafRevelation_Value) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeafRevelation_Value) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Value != nil {
		{
			size, err := m.Value.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *CommitmentRevelation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommitmentRevelation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommitmentRevelation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Right.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Left.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.CommitmentHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CommitmentHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CommitmentEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommitmentEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommitmentEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Commitment.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.CommitmentHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CommitmentHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VerificationVoteEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerificationVoteEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerificationVoteEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.State != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.ProofKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProofKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubmissionHeight != 0 {
		n += 1 + sovTypes(uint64(m.SubmissionHeight))
	}
	if m.IndexInBlock != 0 {
		n += 1 + sovTypes(uint64(m.IndexInBlock))
	}
	return n
}

func (m *ProofRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProofHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ProofType != 0 {
		n += 1 + sovTypes(uint64(m.ProofType))
	}
	l = len(m.PublicInputsHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.VerificationKeyHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.VerificationId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *CommitmentRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ProofVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IndexInBlock != 0 {
		n += 1 + sovTypes(uint64(m.IndexInBlock))
	}
	if m.Result {
		n += 2
	}
	return n
}

func (m *ProofTally) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidVotingPower != 0 {
		n += 1 + sovTypes(uint64(m.ValidVotingPower))
	}
	if m.InvalidVotingPower != 0 {
		n += 1 + sovTypes(uint64(m.InvalidVotingPower))
	}
	return n
}

func (m *FinalProofResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProofHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ProofType != 0 {
		n += 1 + sovTypes(uint64(m.ProofType))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	if m.ValidVotingPower != 0 {
		n += 1 + sovTypes(uint64(m.ValidVotingPower))
	}
	if m.InvalidVotingPower != 0 {
		n += 1 + sovTypes(uint64(m.InvalidVotingPower))
	}
	if m.TotalVotingPower != 0 {
		n += 1 + sovTypes(uint64(m.TotalVotingPower))
	}
	if m.VotingPowerThreshold != 0 {
		n += 1 + sovTypes(uint64(m.VotingPowerThreshold))
	}
	if m.SubmissionHeight != 0 {
		n += 1 + sovTypes(uint64(m.SubmissionHeight))
	}
	if m.FinalizedHeight != 0 {
		n += 1 + sovTypes(uint64(m.FinalizedHeight))
	}
	l = len(m.PublicInputsHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.VerificationKeyHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.VerificationId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *RevealedLeaf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *LeafRevelation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Mode != 0 {
		n += 1 + sovTypes(uint64(m.Mode))
	}
	if m.Payload != nil {
		n += m.Payload.Size()
	}
	return n
}

func (m *LeafRevelation_LeafHash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LeafHash != nil {
		l = len(m.LeafHash)
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *LeafRevelation_Value) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value != nil {
		l = m.Value.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *CommitmentRevelation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommitmentHeight != 0 {
		n += 1 + sovTypes(uint64(m.CommitmentHeight))
	}
	l = m.Left.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.Right.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *CommitmentEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.CommitmentHeight != 0 {
		n += 1 + sovTypes(uint64(m.CommitmentHeight))
	}
	l = m.Commitment.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *VerificationVoteEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ProofKey.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovTypes(uint64(m.State))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProofKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmissionHeight", wireType)
			}
			m.SubmissionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmissionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexInBlock", wireType)
			}
			m.IndexInBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexInBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProofRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofHash = append(m.ProofHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ProofHash == nil {
				m.ProofHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofType", wireType)
			}
			m.ProofType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofType |= ProofType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicInputsHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicInputsHash = append(m.PublicInputsHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicInputsHash == nil {
				m.PublicInputsHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationKeyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationKeyHash = append(m.VerificationKeyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.VerificationKeyHash == nil {
				m.VerificationKeyHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationId = append(m.VerificationId[:0], dAtA[iNdEx:postIndex]...)
			if m.VerificationId == nil {
				m.VerificationId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommitmentRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommitmentRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommitmentRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProofVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexInBlock", wireType)
			}
			m.IndexInBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexInBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Result = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProofTally) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofTally: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofTally: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidVotingPower", wireType)
			}
			m.ValidVotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidVotingPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvalidVotingPower", wireType)
			}
			m.InvalidVotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InvalidVotingPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FinalProofResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FinalProofResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FinalProofResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofHash = append(m.ProofHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ProofHash == nil {
				m.ProofHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofType", wireType)
			}
			m.ProofType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofType |= ProofType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ProofStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidVotingPower", wireType)
			}
			m.ValidVotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidVotingPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvalidVotingPower", wireType)
			}
			m.InvalidVotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InvalidVotingPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVotingPower", wireType)
			}
			m.TotalVotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalVotingPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPowerThreshold", wireType)
			}
			m.VotingPowerThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPowerThreshold |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmissionHeight", wireType)
			}
			m.SubmissionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmissionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedHeight", wireType)
			}
			m.FinalizedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicInputsHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicInputsHash = append(m.PublicInputsHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicInputsHash == nil {
				m.PublicInputsHash = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationKeyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationKeyHash = append(m.VerificationKeyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.VerificationKeyHash == nil {
				m.VerificationKeyHash = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationId = append(m.VerificationId[:0], dAtA[iNdEx:postIndex]...)
			if m.VerificationId == nil {
				m.VerificationId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RevealedLeaf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RevealedLeaf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RevealedLeaf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = append(m.Salt[:0], dAtA[iNdEx:postIndex]...)
			if m.Salt == nil {
				m.Salt = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, ProofVote{})
			if err := m.Votes[len(m.Votes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LeafRevelation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LeafRevelation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LeafRevelation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= LeafRevealMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeafHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.Payload = &LeafRevelation_LeafHash{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RevealedLeaf{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Payload = &LeafRevelation_Value{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommitmentRevelation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommitmentRevelation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommitmentRevelation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentHeight", wireType)
			}
			m.CommitmentHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitmentHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Left", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Left.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Right", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Right.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommitmentEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommitmentEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommitmentEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentHeight", wireType)
			}
			m.CommitmentHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitmentHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Commitment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerificationVoteEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerificationVoteEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerificationVoteEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProofKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= VoteState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
