syntax = "proto3";

package pulsarchain.keyregistry.v1;

import "amino/amino.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "pulsarchain/keyregistry/v1/params.proto";

option go_package = "github.com/node101-io/pulsar-chain/x/keyregistry/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/keyregistry/v1/params";
  }

  // GetUserMinaAddress Queries a list of GetUserMinaAddress items.
  rpc GetUserMinaAddress(QueryGetUserMinaAddressRequest) returns (QueryGetUserMinaAddressResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/keyregistry/v1/get_user_mina_address/{user_cosmos_address}";
  }

  // GetUserCosmosAddress Queries a list of GetUserCosmosAddress items.
  rpc GetUserCosmosAddress(QueryGetUserCosmosAddressRequest) returns (QueryGetUserCosmosAddressResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/keyregistry/v1/get_user_cosmos_address/{user_mina_address}";
  }

  // GetValidatorMinaAddress Queries a list of GetValidatorMinaAddress items.
  rpc GetValidatorMinaPubKey(QueryGetValidatorMinaPubKeyRequest) returns (QueryGetValidatorMinaPubKeyResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/keyregistry/v1/get_validator_mina_pub_key/{validator_cosmos_pub_key}";
  }

  // GetValidatorCosmosAddress Queries a list of GetValidatorCosmosAddress items.
  rpc GetValidatorCosmosPubKey(QueryGetValidatorCosmosPubKeyRequest) returns (QueryGetValidatorCosmosPubKeyResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/keyregistry/v1/get_validator_cosmos_pub_key/{validator_mina_pub_key}";
  }
}

// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params holds all the parameters of this module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// QueryGetUserMinaAddressRequest defines the QueryGetUserMinaAddressRequest message.
message QueryGetUserMinaAddressRequest {
  bytes user_cosmos_address = 1;
}

// QueryGetUserMinaAddressResponse defines the QueryGetUserMinaAddressResponse message.
message QueryGetUserMinaAddressResponse {
  bytes user_mina_address = 1;
}

// QueryGetUserCosmosAddressRequest defines the QueryGetUserCosmosAddressRequest message.
message QueryGetUserCosmosAddressRequest {
  bytes user_mina_address = 1;
}

// QueryGetUserCosmosAddressResponse defines the QueryGetUserCosmosAddressResponse message.
message QueryGetUserCosmosAddressResponse {
  bytes user_cosmos_address = 1;
}

// QueryGetValidatorMinaAddressRequest defines the QueryGetValidatorMinaAddressRequest message.
message QueryGetValidatorMinaPubKeyRequest {
  bytes validator_cosmos_pub_key = 1;
}

// QueryGetValidatorMinaAddressResponse defines the QueryGetValidatorMinaAddressResponse message.
message QueryGetValidatorMinaPubKeyResponse {
  bytes validator_mina_pub_key= 1;
}

// QueryGetValidatorCosmosAddressRequest defines the QueryGetValidatorCosmosAddressRequest message.
message QueryGetValidatorCosmosPubKeyRequest {
  bytes validator_mina_pub_key = 1;
}

// QueryGetValidatorCosmosAddressResponse defines the QueryGetValidatorCosmosAddressResponse message.
message QueryGetValidatorCosmosPubKeyResponse {
  bytes validator_cosmos_pub_key = 1;
}
