syntax = "proto3";

package pulsarchain.bridge.v1;

import "amino/amino.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "pulsarchain/bridge/v1/params.proto";

option go_package = "github.com/node101-io/pulsar-chain/x/bridge/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/bridge/v1/params";
  }

  // ActionsReducedRoot Queries a list of ActionsReducedRoot items.
  rpc ActionsReducedRoot(QueryActionsReducedRootRequest) returns (QueryActionsReducedRootResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/bridge/v1/actions_reduced_root";
  }

  // LatestValidActionHashes Queries a list of LatestValidActionHashes items.
  rpc LatestValidActionHashes(QueryLatestValidActionHashesRequest) returns (QueryLatestValidActionHashesResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/bridge/v1/latest_valid_action_hashes";
  }
}

// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params holds all the parameters of this module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// QueryActionsReducedRootRequest defines the QueryActionsReducedRootRequest message.
message QueryActionsReducedRootRequest {}

// QueryActionsReducedRootResponse defines the QueryActionsReducedRootResponse message.
message QueryActionsReducedRootResponse {
  bytes actions_reduced_root = 1;
}

// QueryLatestValidActionHashesRequest defines the QueryLatestValidActionHashesRequest message.
message QueryLatestValidActionHashesRequest {}

// QueryLatestValidActionHashesResponse defines the QueryLatestValidActionHashesResponse message.
message QueryLatestValidActionHashesResponse {
  int64 latest_fetched_mina_height = 1;
  repeated string valid_action_hashes = 2;
  // start_mina_height is the starting Mina cursor for the current query batch.
  int64 start_mina_height = 3;

  int64 valid_action_hashes_cosmos_block_height = 4;
}
