// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/voteexthandler/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb1c23ae06aadedd, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb1c23ae06aadedd, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryVoteextsByHeightRequest defines the QueryVoteextsByHeightRequest message.
type QueryVoteextsByHeightRequest struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryVoteextsByHeightRequest) Reset()         { *m = QueryVoteextsByHeightRequest{} }
func (m *QueryVoteextsByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVoteextsByHeightRequest) ProtoMessage()    {}
func (*QueryVoteextsByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb1c23ae06aadedd, []int{2}
}
func (m *QueryVoteextsByHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVoteextsByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVoteextsByHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVoteextsByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVoteextsByHeightRequest.Merge(m, src)
}
func (m *QueryVoteextsByHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVoteextsByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVoteextsByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVoteextsByHeightRequest proto.InternalMessageInfo

func (m *QueryVoteextsByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// QueryVoteextsByHeightResponse defines the QueryVoteextsByHeightResponse message.
type QueryVoteextsByHeightResponse struct {
	VoteExts []*VoteExt `protobuf:"bytes,1,rep,name=vote_exts,json=voteExts,proto3" json:"vote_exts,omitempty"`
}

func (m *QueryVoteextsByHeightResponse) Reset()         { *m = QueryVoteextsByHeightResponse{} }
func (m *QueryVoteextsByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVoteextsByHeightResponse) ProtoMessage()    {}
func (*QueryVoteextsByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb1c23ae06aadedd, []int{3}
}
func (m *QueryVoteextsByHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVoteextsByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVoteextsByHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVoteextsByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVoteextsByHeightResponse.Merge(m, src)
}
func (m *QueryVoteextsByHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVoteextsByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVoteextsByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVoteextsByHeightResponse proto.InternalMessageInfo

func (m *QueryVoteextsByHeightResponse) GetVoteExts() []*VoteExt {
	if m != nil {
		return m.VoteExts
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "pulsarchain.voteexthandler.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "pulsarchain.voteexthandler.v1.QueryParamsResponse")
	proto.RegisterType((*QueryVoteextsByHeightRequest)(nil), "pulsarchain.voteexthandler.v1.QueryVoteextsByHeightRequest")
	proto.RegisterType((*QueryVoteextsByHeightResponse)(nil), "pulsarchain.voteexthandler.v1.QueryVoteextsByHeightResponse")
}

func init() {
	proto.RegisterFile("pulsarchain/voteexthandler/v1/query.proto", fileDescriptor_fb1c23ae06aadedd)
}

var fileDescriptor_fb1c23ae06aadedd = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcf, 0x6a, 0x13, 0x41,
	0x18, 0xcf, 0x58, 0x0d, 0x76, 0x7a, 0xd1, 0xb1, 0x88, 0x84, 0x76, 0x95, 0x05, 0xa5, 0x16, 0xbb,
	0xe3, 0xa4, 0x20, 0x14, 0x3d, 0x45, 0x94, 0x9c, 0x44, 0x23, 0x78, 0xf0, 0x12, 0x66, 0x93, 0x61,
	0x77, 0x20, 0x99, 0x6f, 0xbb, 0x33, 0x59, 0xb2, 0x88, 0x17, 0x9f, 0x40, 0xd0, 0x87, 0x10, 0x4f,
	0x3e, 0x46, 0x8f, 0x05, 0x2f, 0x5e, 0x14, 0x49, 0x04, 0x5f, 0x43, 0x76, 0x66, 0x02, 0xb6, 0x92,
	0xad, 0xe9, 0x65, 0x77, 0xf6, 0xe3, 0xf7, 0x77, 0x3e, 0x16, 0xdf, 0xcd, 0x26, 0x23, 0xcd, 0xf3,
	0x41, 0xca, 0xa5, 0xa2, 0x05, 0x18, 0x21, 0xa6, 0x26, 0xe5, 0x6a, 0x38, 0x12, 0x39, 0x2d, 0x18,
	0x3d, 0x9c, 0x88, 0xbc, 0x8c, 0xb2, 0x1c, 0x0c, 0x90, 0xed, 0xbf, 0xa0, 0xd1, 0x49, 0x68, 0x54,
	0xb0, 0xd6, 0x55, 0x3e, 0x96, 0x0a, 0xa8, 0x7d, 0x3a, 0x46, 0x6b, 0x77, 0x00, 0x7a, 0x0c, 0x9a,
	0xc6, 0x5c, 0x0b, 0x27, 0x45, 0x0b, 0x16, 0x0b, 0xc3, 0x19, 0xcd, 0x78, 0x22, 0x15, 0x37, 0x12,
	0x94, 0xc7, 0x6e, 0x26, 0x90, 0x80, 0x3d, 0xd2, 0xea, 0xe4, 0xa7, 0x5b, 0x09, 0x40, 0x32, 0x12,
	0x94, 0x67, 0x92, 0x72, 0xa5, 0xc0, 0x58, 0x8a, 0x5e, 0xe8, 0xd7, 0x87, 0xcf, 0x78, 0xce, 0xc7,
	0x0b, 0xec, 0xbd, 0x7a, 0x6c, 0x35, 0xe9, 0x8b, 0xa9, 0x71, 0xe8, 0x70, 0x13, 0x93, 0x17, 0x55,
	0xde, 0xe7, 0x56, 0xa2, 0x27, 0x0e, 0x27, 0x42, 0x9b, 0xb0, 0x8f, 0xaf, 0x9d, 0x98, 0xea, 0x0c,
	0x94, 0x16, 0xa4, 0x8b, 0x9b, 0xce, 0xea, 0x06, 0xba, 0x85, 0x76, 0x36, 0xda, 0xb7, 0xa3, 0xda,
	0x9b, 0x8a, 0x1c, 0xbd, 0xb3, 0x7e, 0xf4, 0xe3, 0x66, 0xe3, 0xd3, 0xef, 0x2f, 0xbb, 0xa8, 0xe7,
	0xf9, 0xe1, 0x03, 0xbc, 0x65, 0x0d, 0x5e, 0x39, 0x8e, 0xee, 0x94, 0x5d, 0x21, 0x93, 0xd4, 0xf8,
	0x00, 0xe4, 0x3a, 0x6e, 0xa6, 0x76, 0x60, 0x9d, 0x2e, 0xf6, 0xfc, 0x57, 0x38, 0xc4, 0xdb, 0x4b,
	0x78, 0x3e, 0xe2, 0x63, 0xbc, 0xbe, 0x68, 0x58, 0xa5, 0x5c, 0xdb, 0xd9, 0x68, 0xdf, 0x39, 0x23,
	0x65, 0xa5, 0xf5, 0x64, 0x6a, 0x7a, 0x97, 0x0b, 0x77, 0xd0, 0xed, 0x8f, 0x6b, 0xf8, 0x92, 0xb5,
	0x21, 0x9f, 0x11, 0x6e, 0xba, 0x16, 0x84, 0x9d, 0x21, 0xf3, 0xef, 0x35, 0xb6, 0xda, 0xab, 0x50,
	0x5c, 0x81, 0xf0, 0xe0, 0xdd, 0xd7, 0x5f, 0x1f, 0x2e, 0xec, 0x13, 0x46, 0x15, 0x0c, 0x05, 0xbb,
	0xcf, 0xf6, 0x24, 0x50, 0x27, 0xb3, 0x57, 0xbf, 0x7f, 0xf2, 0x1d, 0xe1, 0x2b, 0xa7, 0x2f, 0x86,
	0x3c, 0xfc, 0x9f, 0x0c, 0x4b, 0xd6, 0xd0, 0x7a, 0x74, 0x3e, 0xb2, 0xaf, 0xf2, 0xcc, 0x56, 0xe9,
	0x92, 0xa7, 0x2b, 0x54, 0xf1, 0x13, 0xdd, 0x8f, 0xcb, 0xbe, 0xdb, 0x39, 0x7d, 0xe3, 0xde, 0x6f,
	0x3b, 0x2f, 0x8f, 0x66, 0x01, 0x3a, 0x9e, 0x05, 0xe8, 0xe7, 0x2c, 0x40, 0xef, 0xe7, 0x41, 0xe3,
	0x78, 0x1e, 0x34, 0xbe, 0xcd, 0x83, 0xc6, 0xeb, 0x83, 0x44, 0x9a, 0x74, 0x12, 0x47, 0x03, 0x18,
	0x2f, 0xf5, 0x9a, 0x9e, 0x76, 0x33, 0x65, 0x26, 0x74, 0xdc, 0xb4, 0xff, 0xc1, 0xfe, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xce, 0x6f, 0x6f, 0x58, 0x20, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// VoteextsByHeight Queries a list of VoteextsByHeight items.
	VoteextsByHeight(ctx context.Context, in *QueryVoteextsByHeightRequest, opts ...grpc.CallOption) (*QueryVoteextsByHeightResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/pulsarchain.voteexthandler.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteextsByHeight(ctx context.Context, in *QueryVoteextsByHeightRequest, opts ...grpc.CallOption) (*QueryVoteextsByHeightResponse, error) {
	out := new(QueryVoteextsByHeightResponse)
	err := c.cc.Invoke(ctx, "/pulsarchain.voteexthandler.v1.Query/VoteextsByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// VoteextsByHeight Queries a list of VoteextsByHeight items.
	VoteextsByHeight(context.Context, *QueryVoteextsByHeightRequest) (*QueryVoteextsByHeightResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) VoteextsByHeight(ctx context.Context, req *QueryVoteextsByHeightRequest) (*QueryVoteextsByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteextsByHeight not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulsarchain.voteexthandler.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteextsByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVoteextsByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteextsByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulsarchain.voteexthandler.v1.Query/VoteextsByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteextsByHeight(ctx, req.(*QueryVoteextsByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pulsarchain.voteexthandler.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "VoteextsByHeight",
			Handler:    _Query_VoteextsByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pulsarchain/voteexthandler/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryVoteextsByHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVoteextsByHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVoteextsByHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryVoteextsByHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVoteextsByHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVoteextsByHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VoteExts) > 0 {
		for iNdEx := len(m.VoteExts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VoteExts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVoteextsByHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovQuery(uint64(m.Height))
	}
	return n
}

func (m *QueryVoteextsByHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VoteExts) > 0 {
		for _, e := range m.VoteExts {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVoteextsByHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVoteextsByHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVoteextsByHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVoteextsByHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVoteextsByHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVoteextsByHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteExts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteExts = append(m.VoteExts, &VoteExt{})
			if err := m.VoteExts[len(m.VoteExts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
