// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/voteexthandler/v1/vote_ext_body.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Body defines the VoteExtBody message.
type Body struct {
	InitialValidatorSetRoot []byte `protobuf:"bytes,1,opt,name=initial_validator_set_root,json=initialValidatorSetRoot,proto3" json:"initial_validator_set_root,omitempty"`
	InitialStateRoot        []byte `protobuf:"bytes,2,opt,name=initial_state_root,json=initialStateRoot,proto3" json:"initial_state_root,omitempty"`
	InitialBlockHeight      int64  `protobuf:"varint,3,opt,name=initial_block_height,json=initialBlockHeight,proto3" json:"initial_block_height,omitempty"`
	NewValidatorSetRoot     []byte `protobuf:"bytes,4,opt,name=new_validator_set_root,json=newValidatorSetRoot,proto3" json:"new_validator_set_root,omitempty"`
	NewStateRoot            []byte `protobuf:"bytes,5,opt,name=new_state_root,json=newStateRoot,proto3" json:"new_state_root,omitempty"`
	NewBlockHeight          int64  `protobuf:"varint,6,opt,name=new_block_height,json=newBlockHeight,proto3" json:"new_block_height,omitempty"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_3751769e03004787, []int{0}
}
func (m *Body) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Body.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return m.Size()
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetInitialValidatorSetRoot() []byte {
	if m != nil {
		return m.InitialValidatorSetRoot
	}
	return nil
}

func (m *Body) GetInitialStateRoot() []byte {
	if m != nil {
		return m.InitialStateRoot
	}
	return nil
}

func (m *Body) GetInitialBlockHeight() int64 {
	if m != nil {
		return m.InitialBlockHeight
	}
	return 0
}

func (m *Body) GetNewValidatorSetRoot() []byte {
	if m != nil {
		return m.NewValidatorSetRoot
	}
	return nil
}

func (m *Body) GetNewStateRoot() []byte {
	if m != nil {
		return m.NewStateRoot
	}
	return nil
}

func (m *Body) GetNewBlockHeight() int64 {
	if m != nil {
		return m.NewBlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Body)(nil), "pulsarchain.voteexthandler.v1.Body")
}

func init() {
	proto.RegisterFile("pulsarchain/voteexthandler/v1/vote_ext_body.proto", fileDescriptor_3751769e03004787)
}

var fileDescriptor_3751769e03004787 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0xc2, 0x40,
	0x18, 0x86, 0x39, 0x40, 0x86, 0x0b, 0x31, 0xa4, 0x1a, 0x25, 0x26, 0x5e, 0x88, 0x71, 0x60, 0x90,
	0x96, 0x86, 0xc9, 0xb8, 0x31, 0x39, 0x43, 0xe2, 0xe0, 0x72, 0xb9, 0xd2, 0x2f, 0xf4, 0x62, 0xbd,
	0x8f, 0xb4, 0x1f, 0x05, 0xfe, 0x85, 0x3f, 0xc3, 0x9f, 0xe2, 0xc8, 0xe8, 0x68, 0xe0, 0x8f, 0x98,
	0x5e, 0x69, 0x2c, 0xea, 0x7a, 0xef, 0xfb, 0xdc, 0x3d, 0xb9, 0x97, 0xfb, 0x8b, 0x65, 0x9c, 0xaa,
	0x64, 0x16, 0x29, 0x6d, 0xbc, 0x0c, 0x09, 0x60, 0x4d, 0x91, 0x32, 0x61, 0x0c, 0x89, 0x97, 0xf9,
	0xf6, 0x44, 0xc2, 0x9a, 0x64, 0x80, 0xe1, 0xc6, 0x5d, 0x24, 0x48, 0xe8, 0x5c, 0x57, 0x10, 0xf7,
	0x18, 0x71, 0x33, 0xff, 0xe6, 0xbd, 0xce, 0x9b, 0x63, 0x0c, 0x37, 0xce, 0x03, 0xbf, 0xd2, 0x46,
	0x93, 0x56, 0xb1, 0xcc, 0x54, 0xac, 0x43, 0x45, 0x98, 0xc8, 0x14, 0x48, 0x26, 0x88, 0xd4, 0x65,
	0x3d, 0xd6, 0x6f, 0x4f, 0x2e, 0x0f, 0x8d, 0xa7, 0xb2, 0x30, 0x05, 0x9a, 0x20, 0x92, 0x73, 0xc7,
	0x9d, 0x12, 0x4e, 0x49, 0x11, 0x14, 0x50, 0xdd, 0x42, 0x9d, 0x43, 0x32, 0xcd, 0x03, 0xdb, 0x1e,
	0xf2, 0xf3, 0xb2, 0x1d, 0xc4, 0x38, 0x7b, 0x91, 0x11, 0xe8, 0x79, 0x44, 0xdd, 0x46, 0x8f, 0xf5,
	0x1b, 0x93, 0xf2, 0xa6, 0x71, 0x1e, 0x3d, 0xda, 0xc4, 0x19, 0xf1, 0x0b, 0x03, 0xab, 0xff, 0xc4,
	0x9a, 0xf6, 0x8d, 0x33, 0x03, 0xab, 0x3f, 0x52, 0xb7, 0xfc, 0x34, 0x87, 0x2a, 0x42, 0x27, 0xb6,
	0xdc, 0x36, 0xb0, 0xfa, 0x91, 0xe9, 0xf3, 0x4e, 0xde, 0x3a, 0x12, 0x69, 0x59, 0x91, 0x9c, 0xae,
	0x48, 0x8c, 0xa7, 0x1f, 0x3b, 0xc1, 0xb6, 0x3b, 0xc1, 0xbe, 0x76, 0x82, 0xbd, 0xed, 0x45, 0x6d,
	0xbb, 0x17, 0xb5, 0xcf, 0xbd, 0xa8, 0x3d, 0xdf, 0xcf, 0x35, 0x45, 0xcb, 0xc0, 0x9d, 0xe1, 0xab,
	0x67, 0x30, 0x04, 0x7f, 0xe8, 0x0f, 0x34, 0x7a, 0xc5, 0xcf, 0x0f, 0x8a, 0xb5, 0xd6, 0xbf, 0xf7,
	0xa2, 0xcd, 0x02, 0xd2, 0xa0, 0x65, 0x57, 0x1a, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xa4,
	0x99, 0xeb, 0xda, 0x01, 0x00, 0x00,
}

func (m *Body) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Body) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Body) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewBlockHeight != 0 {
		i = encodeVarintVoteExtBody(dAtA, i, uint64(m.NewBlockHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.NewStateRoot) > 0 {
		i -= len(m.NewStateRoot)
		copy(dAtA[i:], m.NewStateRoot)
		i = encodeVarintVoteExtBody(dAtA, i, uint64(len(m.NewStateRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NewValidatorSetRoot) > 0 {
		i -= len(m.NewValidatorSetRoot)
		copy(dAtA[i:], m.NewValidatorSetRoot)
		i = encodeVarintVoteExtBody(dAtA, i, uint64(len(m.NewValidatorSetRoot)))
		i--
		dAtA[i] = 0x22
	}
	if m.InitialBlockHeight != 0 {
		i = encodeVarintVoteExtBody(dAtA, i, uint64(m.InitialBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.InitialStateRoot) > 0 {
		i -= len(m.InitialStateRoot)
		copy(dAtA[i:], m.InitialStateRoot)
		i = encodeVarintVoteExtBody(dAtA, i, uint64(len(m.InitialStateRoot)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.InitialValidatorSetRoot) > 0 {
		i -= len(m.InitialValidatorSetRoot)
		copy(dAtA[i:], m.InitialValidatorSetRoot)
		i = encodeVarintVoteExtBody(dAtA, i, uint64(len(m.InitialValidatorSetRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVoteExtBody(dAtA []byte, offset int, v uint64) int {
	offset -= sovVoteExtBody(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Body) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InitialValidatorSetRoot)
	if l > 0 {
		n += 1 + l + sovVoteExtBody(uint64(l))
	}
	l = len(m.InitialStateRoot)
	if l > 0 {
		n += 1 + l + sovVoteExtBody(uint64(l))
	}
	if m.InitialBlockHeight != 0 {
		n += 1 + sovVoteExtBody(uint64(m.InitialBlockHeight))
	}
	l = len(m.NewValidatorSetRoot)
	if l > 0 {
		n += 1 + l + sovVoteExtBody(uint64(l))
	}
	l = len(m.NewStateRoot)
	if l > 0 {
		n += 1 + l + sovVoteExtBody(uint64(l))
	}
	if m.NewBlockHeight != 0 {
		n += 1 + sovVoteExtBody(uint64(m.NewBlockHeight))
	}
	return n
}

func sovVoteExtBody(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVoteExtBody(x uint64) (n int) {
	return sovVoteExtBody(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Body) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteExtBody
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Body: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Body: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialValidatorSetRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialValidatorSetRoot = append(m.InitialValidatorSetRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.InitialValidatorSetRoot == nil {
				m.InitialValidatorSetRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialStateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialStateRoot = append(m.InitialStateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.InitialStateRoot == nil {
				m.InitialStateRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBlockHeight", wireType)
			}
			m.InitialBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewValidatorSetRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewValidatorSetRoot = append(m.NewValidatorSetRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.NewValidatorSetRoot == nil {
				m.NewValidatorSetRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewStateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewStateRoot = append(m.NewStateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.NewStateRoot == nil {
				m.NewStateRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewBlockHeight", wireType)
			}
			m.NewBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtBody
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVoteExtBody(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteExtBody
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVoteExtBody(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVoteExtBody
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteExtBody
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteExtBody
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVoteExtBody
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVoteExtBody
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVoteExtBody
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVoteExtBody        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVoteExtBody          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVoteExtBody = fmt.Errorf("proto: unexpected end of group")
)
