// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/voteexthandler/v1/vote_ext.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the voteexthandler module's genesis state.
type VoteExt struct {
	Index         string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Height        uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ValidatorAddr string `protobuf:"bytes,3,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	Signature     []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Body          *Body  `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *VoteExt) Reset()         { *m = VoteExt{} }
func (m *VoteExt) String() string { return proto.CompactTextString(m) }
func (*VoteExt) ProtoMessage()    {}
func (*VoteExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfe772305a00414, []int{0}
}
func (m *VoteExt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VoteExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VoteExt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VoteExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteExt.Merge(m, src)
}
func (m *VoteExt) XXX_Size() int {
	return m.Size()
}
func (m *VoteExt) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteExt.DiscardUnknown(m)
}

var xxx_messageInfo_VoteExt proto.InternalMessageInfo

func (m *VoteExt) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *VoteExt) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VoteExt) GetValidatorAddr() string {
	if m != nil {
		return m.ValidatorAddr
	}
	return ""
}

func (m *VoteExt) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *VoteExt) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*VoteExt)(nil), "pulsarchain.voteexthandler.v1.VoteExt")
}

func init() {
	proto.RegisterFile("pulsarchain/voteexthandler/v1/vote_ext.proto", fileDescriptor_acfe772305a00414)
}

var fileDescriptor_acfe772305a00414 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x1b, 0x6d, 0x2b, 0x8d, 0x3f, 0xe0, 0x50, 0x64, 0x28, 0x1a, 0x06, 0x45, 0x18, 0xc4,
	0x26, 0x8e, 0x2e, 0xc4, 0xa5, 0x05, 0x5f, 0x60, 0x04, 0x17, 0x6e, 0x4a, 0xda, 0x84, 0x99, 0x40,
	0x9b, 0x3b, 0x64, 0xd2, 0x61, 0xfa, 0x16, 0xbe, 0x8c, 0xef, 0xe0, 0xb2, 0x4b, 0x97, 0xd2, 0xbe,
	0x88, 0x34, 0x33, 0xf8, 0xb7, 0x28, 0x6e, 0xc2, 0xbd, 0x87, 0x73, 0x72, 0x0f, 0x1f, 0xbe, 0xcc,
	0x66, 0x93, 0x9c, 0x9b, 0x71, 0xca, 0x95, 0x66, 0x05, 0x58, 0x29, 0x4b, 0x9b, 0x72, 0x2d, 0x26,
	0xd2, 0xb0, 0x22, 0x72, 0xca, 0x50, 0x96, 0x96, 0x66, 0x06, 0x2c, 0x78, 0x27, 0x3f, 0xdc, 0xf4,
	0xb7, 0x9b, 0x16, 0x51, 0xef, 0x90, 0x4f, 0x95, 0x06, 0xe6, 0xde, 0x2a, 0xd1, 0xeb, 0x26, 0x90,
	0x80, 0x1b, 0xd9, 0x7a, 0xaa, 0xd5, 0x8b, 0xcd, 0x57, 0x33, 0x6e, 0xf8, 0x34, 0xaf, 0xbd, 0xd1,
	0xff, 0x1a, 0x0e, 0x47, 0x20, 0xe6, 0x55, 0xe4, 0xf4, 0x15, 0xe1, 0x9d, 0x27, 0xb0, 0xf2, 0xa1,
	0xb4, 0x5e, 0x17, 0xb7, 0x94, 0x16, 0xb2, 0xf4, 0x51, 0x80, 0xc2, 0x4e, 0x5c, 0x2d, 0xde, 0x11,
	0x6e, 0xa7, 0x52, 0x25, 0xa9, 0xf5, 0xb7, 0x02, 0x14, 0x36, 0xe3, 0x7a, 0xf3, 0xce, 0xf1, 0x41,
	0xc1, 0x27, 0x4a, 0x70, 0x0b, 0x66, 0xc8, 0x85, 0x30, 0xfe, 0xb6, 0x8b, 0xed, 0x7f, 0xa9, 0xf7,
	0x42, 0x18, 0xef, 0x18, 0x77, 0x72, 0x95, 0x68, 0x6e, 0x67, 0x46, 0xfa, 0xcd, 0x00, 0x85, 0x7b,
	0xf1, 0xb7, 0xe0, 0xdd, 0xe2, 0xe6, 0xba, 0x8c, 0xdf, 0x0a, 0x50, 0xb8, 0x7b, 0x7d, 0x46, 0x37,
	0x42, 0xa3, 0x03, 0x10, 0xf3, 0xd8, 0x05, 0x06, 0x8f, 0x6f, 0x4b, 0x82, 0x16, 0x4b, 0x82, 0x3e,
	0x96, 0x04, 0xbd, 0xac, 0x48, 0x63, 0xb1, 0x22, 0x8d, 0xf7, 0x15, 0x69, 0x3c, 0xdf, 0x25, 0xca,
	0xa6, 0xb3, 0x11, 0x1d, 0xc3, 0x94, 0x69, 0x10, 0x32, 0xba, 0x8a, 0xfa, 0x0a, 0x58, 0xf5, 0x73,
	0xbf, 0x62, 0x53, 0xfe, 0xa5, 0x63, 0xe7, 0x99, 0xcc, 0x47, 0x6d, 0xc7, 0xe4, 0xe6, 0x33, 0x00,
	0x00, 0xff, 0xff, 0x47, 0x8e, 0x2c, 0xd9, 0xea, 0x01, 0x00, 0x00,
}

func (m *VoteExt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VoteExt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VoteExt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Body != nil {
		{
			size, err := m.Body.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVoteExt(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintVoteExt(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ValidatorAddr) > 0 {
		i -= len(m.ValidatorAddr)
		copy(dAtA[i:], m.ValidatorAddr)
		i = encodeVarintVoteExt(dAtA, i, uint64(len(m.ValidatorAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Height != 0 {
		i = encodeVarintVoteExt(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintVoteExt(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVoteExt(dAtA []byte, offset int, v uint64) int {
	offset -= sovVoteExt(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VoteExt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovVoteExt(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovVoteExt(uint64(m.Height))
	}
	l = len(m.ValidatorAddr)
	if l > 0 {
		n += 1 + l + sovVoteExt(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovVoteExt(uint64(l))
	}
	if m.Body != nil {
		l = m.Body.Size()
		n += 1 + l + sovVoteExt(uint64(l))
	}
	return n
}

func sovVoteExt(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVoteExt(x uint64) (n int) {
	return sovVoteExt(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VoteExt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteExt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VoteExt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VoteExt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoteExt
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoteExt
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExt
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVoteExt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Body == nil {
				m.Body = &Body{}
			}
			if err := m.Body.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVoteExt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteExt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVoteExt(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVoteExt
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVoteExt
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVoteExt
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVoteExt
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVoteExt        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVoteExt          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVoteExt = fmt.Errorf("proto: unexpected end of group")
)
