syntax = "proto3";

package pulsarchain.votepersistence.v1;

import "amino/amino.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "pulsarchain/votepersistence/v1/params.proto";

option go_package = "github.com/node101-io/pulsar-chain/x/votepersistence/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/votepersistence/v1/params";
  }

  // VoteExtensions queries the currently persisted vote extensions.
  rpc VoteExtensions(QueryVoteExtensionsRequest) returns (QueryVoteExtensionsResponse) {
    option (google.api.http).get = "/node101-io/pulsar-chain/votepersistence/v1/vote_extensions";
  }
}

// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params holds all the parameters of this module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// QueryVoteExtensionsRequest defines the QueryVoteExtensionsRequest message.
message QueryVoteExtensionsRequest {}

// StoredVoteExtension defines a persisted Mina validator vote extension.
message StoredVoteExtension {
  bytes mina_public_key = 1;
  bytes vote_extension = 2;
}

// QueryVoteExtensionsResponse defines the QueryVoteExtensionsResponse message.
message QueryVoteExtensionsResponse {
  int64 query_block_height = 1;
  // persisted_vote_extensions_block_height is the signed source/current state
  // height. For vote extensions produced at height N, this value is N-2.
  int64 persisted_vote_extensions_block_height = 2;
  repeated StoredVoteExtension vote_extensions = 3;
}
