// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/keyregistry/v1/address_pair.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AddressPair struct {
	MinaAddr   []byte `protobuf:"bytes,1,opt,name=mina_addr,json=minaAddr,proto3" json:"mina_addr,omitempty"`
	CosmosAddr []byte `protobuf:"bytes,2,opt,name=cosmos_addr,json=cosmosAddr,proto3" json:"cosmos_addr,omitempty"`
}

func (m *AddressPair) Reset()         { *m = AddressPair{} }
func (m *AddressPair) String() string { return proto.CompactTextString(m) }
func (*AddressPair) ProtoMessage()    {}
func (*AddressPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9cea5d1b988cd3, []int{0}
}
func (m *AddressPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddressPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddressPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddressPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressPair.Merge(m, src)
}
func (m *AddressPair) XXX_Size() int {
	return m.Size()
}
func (m *AddressPair) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressPair.DiscardUnknown(m)
}

var xxx_messageInfo_AddressPair proto.InternalMessageInfo

func (m *AddressPair) GetMinaAddr() []byte {
	if m != nil {
		return m.MinaAddr
	}
	return nil
}

func (m *AddressPair) GetCosmosAddr() []byte {
	if m != nil {
		return m.CosmosAddr
	}
	return nil
}

func init() {
	proto.RegisterType((*AddressPair)(nil), "pulsarchain.keyregistry.v1.AddressPair")
}

func init() {
	proto.RegisterFile("pulsarchain/keyregistry/v1/address_pair.proto", fileDescriptor_eb9cea5d1b988cd3)
}

var fileDescriptor_eb9cea5d1b988cd3 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2d, 0x28, 0xcd, 0x29,
	0x4e, 0x2c, 0x4a, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0xcf, 0x4e, 0xad, 0x2c, 0x4a, 0x4d, 0xcf, 0x2c,
	0x2e, 0x29, 0xaa, 0xd4, 0x2f, 0x33, 0xd4, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x8e, 0x2f,
	0x48, 0xcc, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x42, 0x52, 0xae, 0x87, 0xa4,
	0x5c, 0xaf, 0xcc, 0x50, 0xc9, 0x9b, 0x8b, 0xdb, 0x11, 0xa2, 0x23, 0x20, 0x31, 0xb3, 0x48, 0x48,
	0x9a, 0x8b, 0x33, 0x37, 0x33, 0x2f, 0x31, 0x1e, 0x64, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f,
	0x10, 0x07, 0x48, 0x00, 0xa4, 0x46, 0x48, 0x9e, 0x8b, 0x3b, 0x39, 0xbf, 0x38, 0x37, 0xbf, 0x18,
	0x22, 0xcd, 0x04, 0x96, 0xe6, 0x82, 0x08, 0x81, 0x14, 0x38, 0x05, 0x9c, 0x78, 0x24, 0xc7, 0x78,
	0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7,
	0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x59, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e,
	0xae, 0x7e, 0x5e, 0x7e, 0x4a, 0xaa, 0xa1, 0x81, 0xa1, 0x6e, 0x66, 0xbe, 0x3e, 0xc4, 0x61, 0xba,
	0x10, 0x8f, 0x54, 0xa0, 0x78, 0xa5, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0xec, 0x03, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0x26, 0x7c, 0xb2, 0xf2, 0x00, 0x00, 0x00,
}

func (m *AddressPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddressPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddressPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CosmosAddr) > 0 {
		i -= len(m.CosmosAddr)
		copy(dAtA[i:], m.CosmosAddr)
		i = encodeVarintAddressPair(dAtA, i, uint64(len(m.CosmosAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MinaAddr) > 0 {
		i -= len(m.MinaAddr)
		copy(dAtA[i:], m.MinaAddr)
		i = encodeVarintAddressPair(dAtA, i, uint64(len(m.MinaAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAddressPair(dAtA []byte, offset int, v uint64) int {
	offset -= sovAddressPair(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AddressPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MinaAddr)
	if l > 0 {
		n += 1 + l + sovAddressPair(uint64(l))
	}
	l = len(m.CosmosAddr)
	if l > 0 {
		n += 1 + l + sovAddressPair(uint64(l))
	}
	return n
}

func sovAddressPair(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAddressPair(x uint64) (n int) {
	return sovAddressPair(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AddressPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAddressPair
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddressPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddressPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinaAddr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressPair
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAddressPair
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressPair
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinaAddr = append(m.MinaAddr[:0], dAtA[iNdEx:postIndex]...)
			if m.MinaAddr == nil {
				m.MinaAddr = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosAddr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressPair
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAddressPair
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressPair
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosAddr = append(m.CosmosAddr[:0], dAtA[iNdEx:postIndex]...)
			if m.CosmosAddr == nil {
				m.CosmosAddr = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAddressPair(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAddressPair
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAddressPair(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAddressPair
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAddressPair
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAddressPair
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAddressPair
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAddressPair
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAddressPair
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAddressPair        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAddressPair          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAddressPair = fmt.Errorf("proto: unexpected end of group")
)
