// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pulsarchain/keyregistry/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the keyregistry module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params                Params                    `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	UserCosmosToMina      []*UserPublicKeyPair      `protobuf:"bytes,2,rep,name=user_cosmos_to_mina,json=userCosmosToMina,proto3" json:"user_cosmos_to_mina,omitempty"`
	UserMinaToCosmos      []*UserPublicKeyPair      `protobuf:"bytes,3,rep,name=user_mina_to_cosmos,json=userMinaToCosmos,proto3" json:"user_mina_to_cosmos,omitempty"`
	ValidatorCosmosToMina []*ValidatorPublicKeyPair `protobuf:"bytes,4,rep,name=validator_cosmos_to_mina,json=validatorCosmosToMina,proto3" json:"validator_cosmos_to_mina,omitempty"`
	ValidatorMinaToCosmos []*ValidatorPublicKeyPair `protobuf:"bytes,5,rep,name=validator_mina_to_cosmos,json=validatorMinaToCosmos,proto3" json:"validator_mina_to_cosmos,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbaeb2ea35536f14, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetUserCosmosToMina() []*UserPublicKeyPair {
	if m != nil {
		return m.UserCosmosToMina
	}
	return nil
}

func (m *GenesisState) GetUserMinaToCosmos() []*UserPublicKeyPair {
	if m != nil {
		return m.UserMinaToCosmos
	}
	return nil
}

func (m *GenesisState) GetValidatorCosmosToMina() []*ValidatorPublicKeyPair {
	if m != nil {
		return m.ValidatorCosmosToMina
	}
	return nil
}

func (m *GenesisState) GetValidatorMinaToCosmos() []*ValidatorPublicKeyPair {
	if m != nil {
		return m.ValidatorMinaToCosmos
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "pulsarchain.keyregistry.v1.GenesisState")
}

func init() {
	proto.RegisterFile("pulsarchain/keyregistry/v1/genesis.proto", fileDescriptor_dbaeb2ea35536f14)
}

var fileDescriptor_dbaeb2ea35536f14 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x93, 0xdb, 0x7b, 0x0b, 0x37, 0xbd, 0x8b, 0x6b, 0x54, 0x08, 0x59, 0xc4, 0xd2, 0x8d,
	0x45, 0x68, 0xd2, 0x54, 0xf0, 0x01, 0x2a, 0xe2, 0x42, 0x84, 0x50, 0xab, 0x0b, 0x11, 0xc2, 0x34,
	0x1d, 0xd2, 0xa1, 0x4d, 0x4e, 0x98, 0x99, 0x14, 0xf3, 0x16, 0x3e, 0x86, 0x4b, 0x1f, 0xa3, 0xcb,
	0x2e, 0x5d, 0x89, 0xb4, 0x0b, 0x17, 0xbe, 0x84, 0x64, 0xa6, 0x96, 0x46, 0x31, 0x0b, 0x71, 0x13,
	0x86, 0xf0, 0x9f, 0xef, 0x3b, 0x3f, 0x1c, 0xad, 0x99, 0xa4, 0x13, 0x86, 0x68, 0x30, 0x42, 0x24,
	0x76, 0xc6, 0x38, 0xa3, 0x38, 0x24, 0x8c, 0xd3, 0xcc, 0x99, 0xba, 0x4e, 0x88, 0x63, 0xcc, 0x08,
	0xb3, 0x13, 0x0a, 0x1c, 0x74, 0x73, 0x23, 0x69, 0x6f, 0x24, 0xed, 0xa9, 0x6b, 0x6e, 0xa1, 0x88,
	0xc4, 0xe0, 0x88, 0xaf, 0x8c, 0x9b, 0x3b, 0x21, 0x84, 0x20, 0x9e, 0x4e, 0xfe, 0x5a, 0xfd, 0xdd,
	0x2f, 0xd1, 0x25, 0x88, 0xa2, 0x68, 0x65, 0x33, 0xdb, 0x65, 0xc1, 0x74, 0x30, 0x21, 0x81, 0x3f,
	0xc6, 0x99, 0x9f, 0x20, 0x42, 0xe5, 0x44, 0xe3, 0xb5, 0xa2, 0xfd, 0x3b, 0x95, 0x1b, 0x5f, 0x70,
	0xc4, 0xb1, 0x7e, 0xa2, 0x55, 0x25, 0xd2, 0x50, 0xeb, 0x6a, 0xb3, 0xd6, 0x69, 0xd8, 0x5f, 0x37,
	0xb0, 0x3d, 0x91, 0xec, 0xfe, 0x9d, 0x3d, 0xed, 0x29, 0xf7, 0x2f, 0x0f, 0x07, 0x6a, 0x6f, 0x35,
	0xac, 0xdf, 0x68, 0xdb, 0x29, 0xc3, 0xd4, 0x0f, 0x80, 0x45, 0xc0, 0x7c, 0x0e, 0x7e, 0x44, 0x62,
	0x64, 0xfc, 0xaa, 0x57, 0x9a, 0xb5, 0x4e, 0xab, 0x8c, 0x79, 0xc9, 0x30, 0xf5, 0xc4, 0xae, 0x67,
	0x38, 0xf3, 0x10, 0xa1, 0xbd, 0xff, 0x39, 0xe9, 0x58, 0x80, 0xfa, 0x70, 0x4e, 0x62, 0xb4, 0xa6,
	0xe7, 0xcc, 0x9c, 0x2d, 0x2d, 0x46, 0xe5, 0xdb, 0xf4, 0x9c, 0xda, 0x07, 0xe9, 0xd0, 0xc7, 0x9a,
	0x31, 0x45, 0x13, 0x32, 0x44, 0x1c, 0x3e, 0x15, 0xf8, 0x2d, 0x14, 0x9d, 0x32, 0xc5, 0xd5, 0xfb,
	0x6c, 0xd1, 0xb3, 0xbb, 0x66, 0x16, 0xaa, 0x14, 0x64, 0x1f, 0xfa, 0xfc, 0xf9, 0x01, 0xd9, 0x66,
	0xb3, 0xae, 0x37, 0x5b, 0x58, 0xea, 0x7c, 0x61, 0xa9, 0xcf, 0x0b, 0x4b, 0xbd, 0x5b, 0x5a, 0xca,
	0x7c, 0x69, 0x29, 0x8f, 0x4b, 0x4b, 0xb9, 0x3e, 0x0a, 0x09, 0x1f, 0xa5, 0x03, 0x3b, 0x80, 0xc8,
	0x89, 0x61, 0x88, 0xdd, 0xb6, 0xdb, 0x22, 0xe0, 0x48, 0x73, 0x4b, 0x1e, 0xd4, 0x6d, 0xe1, 0xa4,
	0x78, 0x96, 0x60, 0x36, 0xa8, 0x8a, 0x33, 0x3a, 0x7c, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xfa,
	0x37, 0x9e, 0x12, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorMinaToCosmos) > 0 {
		for iNdEx := len(m.ValidatorMinaToCosmos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorMinaToCosmos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ValidatorCosmosToMina) > 0 {
		for iNdEx := len(m.ValidatorCosmosToMina) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorCosmosToMina[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.UserMinaToCosmos) > 0 {
		for iNdEx := len(m.UserMinaToCosmos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserMinaToCosmos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.UserCosmosToMina) > 0 {
		for iNdEx := len(m.UserCosmosToMina) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserCosmosToMina[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.UserCosmosToMina) > 0 {
		for _, e := range m.UserCosmosToMina {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.UserMinaToCosmos) > 0 {
		for _, e := range m.UserMinaToCosmos {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorCosmosToMina) > 0 {
		for _, e := range m.ValidatorCosmosToMina {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorMinaToCosmos) > 0 {
		for _, e := range m.ValidatorMinaToCosmos {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserCosmosToMina", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserCosmosToMina = append(m.UserCosmosToMina, &UserPublicKeyPair{})
			if err := m.UserCosmosToMina[len(m.UserCosmosToMina)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserMinaToCosmos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserMinaToCosmos = append(m.UserMinaToCosmos, &UserPublicKeyPair{})
			if err := m.UserMinaToCosmos[len(m.UserMinaToCosmos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorCosmosToMina", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorCosmosToMina = append(m.ValidatorCosmosToMina, &ValidatorPublicKeyPair{})
			if err := m.ValidatorCosmosToMina[len(m.ValidatorCosmosToMina)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorMinaToCosmos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorMinaToCosmos = append(m.ValidatorMinaToCosmos, &ValidatorPublicKeyPair{})
			if err := m.ValidatorMinaToCosmos[len(m.ValidatorMinaToCosmos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
